[package]
name = "product-translation-llm"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
application = { workspace = true }
localization = { workspace = true }
indexmap = { workspace = true }
large-language-model = { workspace = true }
product-core = { workspace = true }
product-service = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
