[package]
name = "billing-service"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
common = { workspace = true }
serde-email = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
user-core = { workspace = true }
user-service = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
