[package]
name = "partner-shop-application-lambda"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "partner-shop-application-lambda"
path = "src/main.rs"

[dependencies]
common = { workspace = true }
partner-shop-application = { workspace = true, features = ["service"] }
notification = { workspace = true, features = ["service"] }
shop = { workspace = true, features = ["service", "dynamodb"] }
user = { workspace = true, features = ["service"] }
serde = { workspace = true }
serde_json = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-sesv2 = { workspace = true }
aws-sdk-s3 = { workspace = true }
lambda_runtime = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
time = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
partner-shop-application = { workspace = true, features = ["full"] }
notification = { workspace = true, features = ["full"] }
shop = { workspace = true, features = ["full"] }
user = { workspace = true, features = ["full"] }
common = { workspace = true, features = ["test-data"] }
test-api = { workspace = true, features = ["dynamodb"] }
serial_test = { workspace = true }
fake = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
time = { workspace = true }
serde_json = { workspace = true }
