[package]
name = "aura-historia-parent"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-tests = { workspace = true }
cognito = { workspace = true }
cognito-post-confirmation = { workspace = true }
common = { workspace = true }
search-filter = { workspace = true }
search-filter-api = { workspace = true }
shop = { workspace = true }
shop-api = { workspace = true }
shop-lambda = { workspace = true }
product = { workspace = true }
product-api = { workspace = true }
product-classification = { workspace = true }
product-classification-api = { workspace = true }
product-classification-lambda = { workspace = true }
product-watchlist-api = { workspace = true }
product-lambda = { workspace = true }
test-api = { workspace = true }
user = { workspace = true }
user-api = { workspace = true }
user-lambda = { workspace = true }
mail = { workspace = true }
mail-lambda-send = { workspace = true }
product-pipeline = { workspace = true }
fxrate = { workspace = true }
fxrate-lambda = { workspace = true }

[workspace]
members = [
    "src/aws-tests",
    "src/cognito",
    "src/cognito-post-confirmation",
    "src/common",
    "src/search-filter",
    "src/search-filter-api",
    "src/product",
    "src/product-api",
    "src/product-classification",
    "src/product-classification-api",
    "src/product-classification-lambda",
    "src/product-watchlist-api",
    "src/product-lambda",
    "src/test-api",
    "src/shop",
    "src/shop-api",
    "src/shop-lambda",
    "src/user",
    "src/user-api",
    "src/user-lambda",
    "src/mail",
    "src/mail-lambda-send",
    "src/product-pipeline",
    "src/fxrate",
    "src/fxrate-lambda",
]

[workspace.dependencies]
accept-language = "3.1.0"
async-stream = "0.3.6"
async-trait = "0.1.89"
aws-config = "1.8.14"
aws-sdk-account = "1.97.0"
aws-sdk-autoscaling = "1.109.0"
aws-sdk-dynamodb = "1.105.0"
aws-sdk-lambda = "1.100.0"
aws-sdk-opensearch = "1.113.0"
aws-sdk-sqs = "1.94.0"
aws-sdk-sesv2 = "1.113.0"
aws-sdk-s3 = "1.123.0"
aws-sdk-cloudwatch = "1.104.0"
aws_lambda_events = { version = "1.0.3", default-features = false }
common = { path = "src/common" }
derive_builder = "0.20.2"
fake = { version = "4.4.0", features = ["derive", "time", "uuid", "url"] }
field = "0.1.0"
search-filter = { path = "src/search-filter" }
search-filter-api = { path = "src/search-filter-api" }
shop = { path = "src/shop" }
shop-lambda = { path = "src/shop-lambda" }
shop-lambda-opensearch-index = { path = "src/shop-lambda/src/shop-lambda-opensearch-index" }
shop-api = { path = "src/shop-api" }
mail = { path = "src/mail" }
mail-core = { path = "src/mail/src/mail-core" }
mail-lambda-send = { path = "src/mail-lambda-send" }
futures = { version = "0.3.31", default-features = false }
hex = "0.4.3"
http = "1.4.0"
httpdate = "1.0.3"
product = { path = "src/product" }
product-api = { path = "src/product-api" }
product-classification = { path = "src/product-classification" }
product-classification-api = { path = "src/product-classification-api" }
product-classification-lambda = { path = "src/product-classification-lambda" }
product-watchlist-api = { path = "src/product-watchlist-api" }
product-lambda = { path = "src/product-lambda" }
product-pipeline-common = { path = "src/product-pipeline/src/product-pipeline-common" }
product-pipeline-translate = { path = "src/product-pipeline/src/product-pipeline-translate" }
product-pipeline-embed-text = { path = "src/product-pipeline/src/product-pipeline-embed-text" }
product-pipeline-extract-attribute = { path = "src/product-pipeline/src/product-pipeline-extract-attribute" }
product-pipeline = { path = "src/product-pipeline" }
product-pipeline-asg-scale-control = { path = "src/product-pipeline/src/product-pipeline-asg-scale-control" }
product-lambda-materialize-dynamodb = { path = "src/product-lambda/src/product-lambda-materialize-dynamodb" }
product-lambda-materialize-opensearch = { path = "src/product-lambda/src/product-lambda-materialize-opensearch" }
product-lambda-update-notify-user = { path = "src/product-lambda/src/product-lambda-update-notify-user" }
itertools = "0.14.0"
lambda_runtime = "1.0.2"
libc = "0.2.181"
mockall = "0.14.0"
opensearch = { version = "2.3.0", default-features = false, features = [
    "aws-auth",
    "rustls-tls",
] }
quote = "1.0.44"
reqwest = { version = "0.12.28", default-features = false, features = [
    "rustls-tls",
] }
rstest = "0.26.1"
serde = "1.0.228"
serde_dynamo = "4.3.0"
serde_json = "1.0.149"
serde_fields = "0.1.0"
serial_test = "3.3.1"
sha2 = "0.10.9"
aws-tests = { path = "src/aws-tests" }
aws-tests-common = { path = "src/aws-tests/src/aws-tests-common" }
smoking-tests = { path = "src/aws-tests/src/smoking-tests" }
staging-data = { path = "src/aws-tests/src/staging-data" }
staging-tests = { path = "src/aws-tests/src/staging-tests" }
strum = "0.27.2"
strum_macros = "0.27.2"
syn = "2.0.115"
test-api = { path = "src/test-api" }
test-api-macros = { path = "src/test-api/src/test-api-macros" }
testcontainers = "0.24.0"
testcontainers-modules = "0.12.1"
thiserror = "2.0.18"
time = "0.3.47"
tokio = { version = "1.49.0", default-features = false }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
typed-builder = "0.23.2"
url = "2.5.8"
uuid = "1.21.0"
walkdir = "2.5.0"
futures-util = "0.3.31"
proc-macro2 = "1.0.106"
smoking-tests-macros = { path = "src/aws-tests/src/smoking-tests/src/smoking-tests-macros" }
staging-tests-macros = { path = "src/aws-tests/src/staging-tests/src/staging-tests-macros" }
user = { path = "src/user" }
user-api = { path = "src/user-api" }
user-lambda = { path = "src/user-lambda" }
cognito = { path = "src/cognito" }
user-lambda-fanout-update-watchlist = { path = "src/user-lambda/src/user-lambda-fanout-update-watchlist" }
cognito-post-confirmation = { path = "src/cognito-post-confirmation" }
serde-email = "3.2.0"
handlebars = "6.4.0"
once_cell = "1.21.3"
openssl = { version = "0.10.75", default-features = false }
jsonwebtokens = "1.2.0"
jsonwebtokens-cognito = "0.1.1"
aws-sdk-cognitoidentityprovider = "1.109.0"
html-escape = "0.2.13"
pyo3 = "0.27.2"
pyo3-ffi = "0.27.0"
regex = "1.12.3"
fxrate = { path = "src/fxrate" }
fxrate-lambda = { path = "src/fxrate-lambda" }
slug = "0.1.6"
