[rules]
ci-determinator = []
application = []
platform-postgres = ["application"]
common = ["application", "platform-postgres"]
geo = []
smoking-tests-macros = []
test-api-macros = []
aura-historia-worker = ["application", "common", "embedding", "platform-postgres", "fxrate-postgres", "large-language-model", "notification-dynamodb", "notification-service", "product-core", "product-opensearch", "product-postgres", "product-service", "search-filter-opensearch", "search-filter-postgres", "search-filter-service", "user-postgres", "watchlist-postgres"]
cloudwatch-log-retention-lambda = ["common"]
cognito = ["common"]
embedding = ["image-fetcher"]
image-fetcher = []
large-language-model = ["common", "image-fetcher"]
shop = ["common", "geo"]
shop-core = ["common", "geo"]
user-core = ["common", "geo"]
watchlist-core = ["common"]
fxrate-core = ["common", "strum"]
fxrate-service = ["common", "fxrate-core"]
fxrate-postgres = ["common", "fxrate-core", "platform-postgres", "fxrate-service", "strum"]
fxrate-fxratesapi = ["common", "fxrate-core", "fxrate-service", "reqwest", "strum"]
fxrate-lambda = ["common", "fxrate-fxratesapi", "fxrate-postgres", "fxrate-service"]
oauth-core = ["common", "user-core"]
partner-shop-application = ["common", "geo", "shop"]
product = ["common", "geo", "shop"]
product-core = ["common", "geo", "shop-core", "strum"]
shop-lambda-opensearch-index = ["common", "shop"]
shop-partner-core = ["common", "shop-core"]
user = ["cognito", "common", "geo"]
user-service = ["application", "common", "geo", "user-core"]
cognito-post-confirmation = ["common", "user-postgres", "user-service"]
crawler = ["common", "product", "shop"]
newsletter-api = ["cognito", "common", "user"]
notification-core = ["common", "product-core"]
oauth = ["common", "user"]
oauth-service = ["common", "oauth-core", "user-core", "user-service"]
partner-shop-application-api = ["common", "partner-shop-application", "shop", "user"]
product-lambda-ingest-partner-products = ["common", "geo", "product", "shop"]
product-lambda-materialize-opensearch = ["common", "product"]
product-service = ["application", "common", "embedding", "fxrate-core", "fxrate-service", "geo", "html-to-markdown-rs", "notification-core", "notification-service", "product-core", "shop-core", "shop-service"]
product-watchlist = ["common", "product", "user"]
search-filter-core = ["common", "product-core"]
shop-api = ["cognito", "common", "shop", "user"]
shop-lambda = ["shop-lambda-opensearch-index"]
shop-service = ["application", "common", "geo", "openssl", "shop-core", "user-service"]
shopify-lambda = ["common", "fxrate-postgres", "product-core", "product-postgres", "product-service", "shop-postgres", "shop-service"]
stripe-api = ["common", "user"]
stripe-lambda = ["common", "user-core", "user-postgres", "user-service"]
user-api = ["common", "geo", "user"]
user-dynamodb = ["common", "user-core", "user-service"]
user-lambda-index-opensearch = ["common", "user"]
user-postgres = ["common", "geo", "platform-postgres", "user-core", "user-service"]
user-zoho = ["common", "user-core", "user-service"]
watchlist-service = ["application", "common", "fxrate-core", "fxrate-service", "notification-core", "notification-service", "product-core", "product-service", "user-core", "user-service", "watchlist-core"]
notification-service = ["common", "notification-core"]
oauth-api = ["common", "oauth", "user"]
oauth-dynamodb = ["common", "oauth-core", "oauth-service", "user-core"]
product-api-partner = ["cognito", "common", "geo", "product", "product-lambda-ingest-partner-products", "shop", "user"]
product-opensearch = ["common", "fxrate-core", "geo", "product-core", "product-service", "shop-core"]
product-postgres = ["common", "geo", "platform-postgres", "product-core", "product-service"]
search-filter = ["common", "embedding", "geo", "product", "shop", "user"]
search-filter-service = ["application", "common", "embedding", "fxrate-core", "fxrate-service", "geo", "large-language-model", "notification-core", "notification-service", "product-core", "product-service", "search-filter-core", "shop-core", "user-core", "user-service"]
shop-partner-service = ["application", "common", "geo", "notification-core", "notification-service", "shop-core", "shop-partner-core", "shop-service", "user-core", "user-service"]
shop-postgres = ["common", "geo", "platform-postgres", "shop-core", "shop-service"]
watchlist-postgres = ["common", "platform-postgres", "product-service", "watchlist-core", "watchlist-service"]
webhook-api = ["cognito", "common", "geo", "product", "product-lambda-ingest-partner-products", "shop", "user"]
notification = ["common", "product", "search-filter", "user"]
notification-dynamodb = ["common", "notification-core", "notification-service", "product", "product-core"]
product-lambda-delete-product = ["common", "product", "product-watchlist", "search-filter"]
search-filter-lambda-opensearch-sync = ["common", "search-filter"]
search-filter-opensearch = ["common", "fxrate-core", "geo", "product-core", "product-opensearch", "product-service", "search-filter-core", "search-filter-service", "shop-core"]
search-filter-postgres = ["common", "geo", "platform-postgres", "product-core", "search-filter-core", "search-filter-service", "shop-core"]
shop-partner-postgres = ["common", "platform-postgres", "shop-core", "shop-partner-core", "shop-partner-service", "shop-service"]
user-lambda-tier-update = ["common", "product-watchlist", "search-filter", "user"]
aura-historia-api = ["billing-service", "billing-stripe", "common", "platform-postgres", "embedding", "fxrate-postgres", "geo", "notification-core", "notification-dynamodb", "notification-service", "oauth-core", "oauth-dynamodb", "oauth-service", "product-core", "product-opensearch", "product-postgres", "product-service", "search-filter-postgres", "search-filter-service", "shop-core", "shop-partner-core", "shop-partner-postgres", "shop-partner-service", "shop-postgres", "shop-service", "user-core", "user-dynamodb", "user-postgres", "user-service", "user-zoho", "watchlist-core", "watchlist-postgres", "watchlist-service"]
aws-tests-common = ["common", "notification", "product", "product-watchlist", "search-filter", "shop", "user"]
notification-api = ["common", "notification", "user"]
notification-send = ["common", "notification", "user"]
partner-shop-application-lambda = ["common", "geo", "notification", "partner-shop-application", "shop", "user"]
product-lambda-update-notify-user = ["common", "notification", "product", "product-watchlist", "user"]
product-personalization = ["common", "notification", "product", "product-watchlist", "search-filter", "user"]
search-filter-lambda-percolate-product = ["common", "notification", "product", "search-filter", "user"]
search-filter-periodic-match = ["common", "notification", "product", "search-filter", "user"]
user-lambda = ["user-lambda-index-opensearch", "user-lambda-tier-update"]
product-api = ["cognito", "common", "embedding", "notification", "product", "product-personalization", "product-watchlist", "search-filter", "user"]
product-lambda = ["product-lambda-delete-product", "product-lambda-ingest-partner-products", "product-lambda-materialize-opensearch", "product-lambda-update-notify-user"]
product-watchlist-api = ["cognito", "common", "notification", "product", "product-personalization", "product-watchlist", "search-filter", "shop", "user"]
search-filter-api = ["common", "embedding", "geo", "notification", "product", "product-personalization", "product-watchlist", "search-filter", "shop", "user"]
search-filter-lambda = ["search-filter-lambda-opensearch-sync", "search-filter-lambda-percolate-product"]
smoking-tests = ["aws-tests-common", "product", "smoking-tests-macros"]
test-api = ["aws-tests-common", "common", "test-api-macros", "user"]
acceptance-tests = ["aws-tests-common", "common", "notification", "partner-shop-application", "product", "product-watchlist", "search-filter", "search-filter-periodic-match", "shop", "test-api", "user"]
aws-tests = ["aws-tests-common", "smoking-tests"]
billing-service = ["common", "user-core", "user-service"]
billing-stripe = ["billing-service", "common"]
aura-historia-parent = ["acceptance-tests", "application", "aura-historia-api", "aura-historia-worker", "aws-tests", "platform-postgres", "billing-service", "billing-stripe", "cloudwatch-log-retention-lambda", "cognito", "cognito-post-confirmation", "common", "embedding", "image-fetcher", "fxrate-lambda", "large-language-model", "geo", "newsletter-api", "notification", "notification-api", "notification-core", "notification-dynamodb", "notification-send", "notification-service", "oauth", "oauth-api", "oauth-core", "oauth-dynamodb", "oauth-service", "partner-shop-application", "partner-shop-application-api", "partner-shop-application-lambda", "product", "product-api", "product-api-partner", "product-core", "product-lambda", "product-lambda-delete-product", "fxrate-core", "fxrate-service", "fxrate-postgres", "fxrate-fxratesapi", "product-opensearch", "product-personalization", "product-postgres", "product-service",  "product-watchlist", "product-watchlist-api", "search-filter", "search-filter-api", "search-filter-core", "search-filter-lambda", "search-filter-opensearch", "search-filter-periodic-match", "search-filter-postgres", "search-filter-service", "shop", "shop-api", "shop-core", "shop-lambda", "shop-partner-core", "shop-partner-postgres", "shop-partner-service", "shop-postgres", "shop-service", "shopify-lambda", "stripe-api", "stripe-lambda", "test-api", "user", "user-api", "user-core", "user-dynamodb", "user-lambda", "user-postgres", "user-service", "user-zoho", "watchlist-core", "watchlist-postgres", "watchlist-service", "webhook-api"]
[options]
strict = true
check_dev_deps = false
unmatched_config_entries = "warn"
