sonar.projectKey=aura-historia_backend
sonar.organization=aura-historia
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.language=rust

sonar.exclusions=**/*.html

sonar.cpd.exclusions=**/*test.rs,**/tests/**,**/__tests__/**,**/main.rs
sonar.coverage.exclusions=**/main.rs
sonar.rust.lcov.reportPaths=coverage.lcov

sonar.python.version=3.12
