[package]
name = "search-filter-data"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
item = { workspace = true, features = ["data"] }
search-filter-core = { workspace = true }
time = { workspace = true }
serde = { workspace = true }

# Optional
fake = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }
search-filter-data = { workspace = true, features = ["test-data"] }
rstest = { workspace = true }

[features]
default = []
test-data = ["fake", "common/test-data", "search-filter-core/test-data"]
