[package]
name = "notification-dynamodb"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
common = { workspace = true, features = ["dynamodb"] }
field = { workspace = true }
localization = { workspace = true }
money = { workspace = true }
notification-core = { workspace = true }
notification-service = { workspace = true }
product = { workspace = true, features = ["dynamodb"] }
product-core = { workspace = true }
serde = { workspace = true }
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+1"] }
serde_fields = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }

# Optional
fake = { workspace = true, optional = true }
mockall = { workspace = true }

[dev-dependencies]
notification-dynamodb = { workspace = true, features = ["test-data", "mock"] }
test-api = { workspace = true, features = ["dynamodb"] }
serial_test = { workspace = true }
rstest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[features]
default = []
mock = []
test-data = ["fake", "common/test-data", "notification-core/test-data", "product/test-data", "product-core/test-data"]
