[package]
name = "user-api"
version = "0.1.0"
edition = "2024"

[dependencies]
geo = { workspace = true }
common = { workspace = true, features = ["api", "opensearch"] }
user = { workspace = true, features = ["dynamodb", "service", "data", "cognito", "opensearch"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_qs = { workspace = true }
serde-email = { workspace = true }
serde_fields = { workspace = true }
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+1"] }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-cognitoidentityprovider = { workspace = true }
aws-config = { workspace = true }
lambda_runtime = { workspace = true }
aws_lambda_events = { workspace = true, features = ["apigw"] }
time = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
async-trait = { workspace = true }
mockall = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
http = { workspace = true }
opensearch = { workspace = true }
url = { workspace = true }

[dev-dependencies]
test-api = { workspace = true, features = ["api-gateway", "dynamodb", "opensearch"] }
serial_test = { workspace = true }
fake = { workspace = true }
user = { workspace = true, features = ["test-data"] }
common = { workspace = true, features = ["test-data"] }
isocountry = { workspace = true }
