[package]
name = "watchlist-service"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
application = { workspace = true }
common = { workspace = true }
fxrate-core = { workspace = true }
fxrate-service = { workspace = true }
localization = { workspace = true }
money = { workspace = true }
notification-service = { workspace = true }
product-core = { workspace = true }
product-service = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
user-core = { workspace = true }
user-service = { workspace = true }
watchlist-core = { workspace = true }

[dev-dependencies]
notification-core = { workspace = true }
serde-email = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
url = { workspace = true }
