[package]
name = "aura-historia-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
