[package]
name = "notification-email-aws"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-sdk-sesv2 = { workspace = true }
application = { workspace = true }
domain-primitives = { workspace = true }
localization = { workspace = true }
money = { workspace = true }
product-listing-core = { workspace = true }
user-core = { workspace = true }
handlebars = { workspace = true }
notification-core = { workspace = true }
notification-email = { workspace = true }
notification-service = { workspace = true }
serde_json = { workspace = true }


[dev-dependencies]
listing-source-core = { workspace = true }
party-core = { workspace = true }
rstest = { workspace = true }
url = { workspace = true }
