[package]
name = "product-pipeline"
version = "0.1.0"
edition = "2024"

[dependencies]
product-pipeline-asg-scale-persist-up = { workspace = true }
product-pipeline-asg-scale-control = { workspace = true }
product-pipeline-common = { workspace = true }
product-pipeline-init = { workspace = true }
product-pipeline-translate = { workspace = true }
product-pipeline-embed-text = { workspace = true }
product-pipeline-extract-attribute = { workspace = true }
product-pipeline-complete = { workspace = true }
product-pipeline-test = { workspace = true }
