[package]
name = "oauth-dynamodb"
version = "0.1.0"
edition = "2024"

[dependencies]
fake = { workspace = true, optional = true }
credential-core = { workspace = true }
application = { workspace = true }
async-trait = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
oauth-core = { workspace = true }
oauth-service = { workspace = true }
serde = { workspace = true }
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+1"] }
serde_fields = { workspace = true }
time = { workspace = true, features = ["serde"] }
url = { workspace = true, features = ["serde"] }
user-core = { workspace = true }

[dev-dependencies]
oauth-dynamodb = { workspace = true, features = ["test-data"] }
test-api = { workspace = true, features = ["dynamodb"] }
rstest = { workspace = true }
serial_test = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[features]
default = []
test-data = ["fake", "oauth-core/test-data", "oauth-service/test-data", "user-core/test-data"]
