pub const STATUS_PENDING_REVIEW: &str = "PENDING_REVIEW";
pub const STATUS_APPROVED: &str = "APPROVED";
pub const STATUS_REJECTED: &str = "REJECTED";
pub const STATUS_NEEDS_REPAIR: &str = "NEEDS_REPAIR";
pub const STATUS_SUPERSEDED: &str = "SUPERSEDED";
