[package]
name = "partner-shop-application"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
shop = { workspace = true, features = ["service", "dynamodb"] }
serde = { workspace = true }
serde_fields = { workspace = true }
time = { workspace = true }
async-trait = { workspace = true }
mockall = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
url = { workspace = true }

# Optional
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+1"], optional = true }
serde_json = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
aws-sdk-dynamodb = { workspace = true, optional = true }
fake = { workspace = true, optional = true }

[dev-dependencies]
partner-shop-application = { workspace = true, features = ["full"] }
test-api = { workspace = true, features = ["dynamodb"] }
serial_test = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[features]
default = []
dynamodb = ["aws-sdk-dynamodb", "serde_dynamo", "serde_dynamo/aws-sdk-dynamodb+1", "serde_json", "tracing", "common/dynamodb"]
service = ["dynamodb"]
test-data = ["fake", "common/test-data", "shop/test-data"]
full = ["test-data", "dynamodb", "service"]
