[package]
name = "product-lambda-materialize-opensearch"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["dynamodb", "event_bridge", "api", "opensearch"] }
product = { workspace = true, features = ["dynamodb", "opensearch"] }
product-classification = { workspace = true }
lambda_runtime = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws_lambda_events = { workspace = true, features = [
    "sqs",
    "dynamodb",
    "eventbridge",
] }
serde_json = { workspace = true }
serde_dynamo = { workspace = true }
tokio = { workspace = true, features = ["macros", "sync"] }
tracing-subscriber = { workspace = true, features = ["json"] }
tracing = { workspace = true }
opensearch = { workspace = true }
url = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
product-classification = { workspace = true, features = ["test-data"] }
product = { workspace = true, features = ["test-data"] }
rstest = { workspace = true }
serde = { workspace = true }
url = { workspace = true }
fake = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
serde_dynamo = { workspace = true }
