[package]
name = "product-core"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
domain-primitives = { workspace = true }
geo = { workspace = true }
html-escape = { workspace = true }
indexmap = { workspace = true }
isocountry = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_fields = { workspace = true }
shop-core = { workspace = true }
strum = { workspace = true }
time = { workspace = true, features = ["local-offset", "macros", "formatting"] }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true }

# Optional
fake = { workspace = true, optional = true }

[dev-dependencies]
rstest = { workspace = true }

[features]
default = []
test-data = ["fake", "common/test-data", "domain-primitives/test-data", "geo/test-data", "shop-core/test-data"]
