[package]
name = "test-api"
version = "0.1.0"
edition = "2024"

[dependencies]
application = { workspace = true }
test-api-macros = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true, optional = true }
derive_builder = { workspace = true }
serial_test = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true, features = ["localstack", "postgres"] }
sqlx = { workspace = true, optional = true }
aws-config = { workspace = true }
aws-sdk-account = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
tracing = { workspace = true }
typed-builder = { workspace = true }
libc = { workspace = true }
ctrlc = { workspace = true }

uuid = { workspace = true }

# Optional deps
aws_lambda_events = { workspace = true, optional = true, features = ["apigw"] }
opensearch = { workspace = true, optional = true, features = ["aws-auth"] }
aws-sdk-opensearch = { workspace = true, optional = true }
aws-sdk-sqs = { workspace = true, optional = true }
aws-sdk-eventbridge = { workspace = true, optional = true }
aws-sdk-cloudformation = { workspace = true, optional = true }
aws-sdk-s3 = { workspace = true, optional = true }
mrml = { workspace = true, optional = true }
aws-sdk-cognitoidentityprovider = { workspace = true, optional = true}
zip = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
futures-util = { workspace = true }

reqwest = { workspace = true, optional = true, features = ["json"] }
base64 = { workspace = true, optional = true }
aws-sdk-sesv2 = { workspace = true, optional = true }

[dev-dependencies]
test-api = { workspace = true, features = [
    "api-gateway",
    "cloudformation",
    "opensearch",
    "postgres",
    "ses",
    "sqs",
    "cognito",
    "sequin"
]}
rstest = { workspace = true }
aura-historia-worker = { workspace = true }
product-listing-core = { workspace = true }

[features]
default = []
api-gateway = ["aws_lambda_events", "aws_lambda_events/apigw"]
aura-historia-api = ["dep:axum"]
opensearch = ["dep:opensearch", "dep:aws-sdk-opensearch"]
postgres = ["dep:sqlx"]
sequin = ["dep:base64", "dep:reqwest", "postgres"]
sqs = ["dep:aws-sdk-sqs"]
eventbridge = ["dep:aws-sdk-eventbridge"]
cognito = ["dep:aws-sdk-cognitoidentityprovider"]
ses = ["dep:aws-sdk-sesv2", "dep:reqwest"]
cloudformation = ["dep:aws-sdk-cloudformation", "dep:aws-sdk-s3", "dep:zip", "dep:futures", "dep:mrml", "cognito", "opensearch", "sqs", "ses", "eventbridge"]
