[package]
name = "test-api"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
test-api-macros = { workspace = true }
async-trait = { workspace = true }
derive_builder = { workspace = true }
hex = { workspace = true }
serial_test = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["full"] }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true, features = ["localstack", "postgres"] }
sqlx = { workspace = true, optional = true }
aws-config = { workspace = true }
aws-sdk-account = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
tracing = { workspace = true }
typed-builder = { workspace = true }
walkdir = { workspace = true }
libc = { workspace = true }
fake = { workspace = true }
uuid = { workspace = true }

# Optional deps
aws_lambda_events = { workspace = true, optional = true, features = ["apigw"] }
opensearch = { workspace = true, optional = true, features = ["aws-auth"] }
aws-sdk-opensearch = { workspace = true, optional = true }
aws-sdk-dynamodb = { workspace = true, optional = true }
serde_dynamo = { workspace = true, optional = true, features = [
    "aws-sdk-dynamodb+1",
] }
aws-sdk-sqs = { workspace = true, optional = true }
aws-sdk-cloudformation = { workspace = true, optional = true }
aws-sdk-s3 = { workspace = true, optional = true }
aws-sdk-cognitoidentityprovider = { workspace = true, optional = true}
aws-tests-common = { workspace = true, optional = true }
zip = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
user = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }

[dev-dependencies]
test-api = { workspace = true, features = [
    "api-gateway",
    "cloudformation",
    "dynamodb",
    "opensearch",
    "rds",
    "sqs",
    "mail",
    "cognito"
]}
rstest = { workspace = true }

[features]
default = []
api-gateway = ["aws_lambda_events", "aws_lambda_events/apigw"]
dynamodb = ["dep:aws-sdk-dynamodb", "serde_dynamo"]
opensearch = ["dep:opensearch", "dep:aws-sdk-opensearch"]
rds = ["dep:sqlx"]
sqs = ["dep:aws-sdk-sqs"]
cognito = ["dep:aws-sdk-cognitoidentityprovider", "user/full"]
mail = ["reqwest"]
cloudformation = ["dep:aws-sdk-cloudformation", "dep:aws-sdk-s3", "dep:aws-tests-common", "dep:zip", "dep:futures", "cognito"]
