[package]
name = "product-pipeline-test"
version = "0.1.0"
edition = "2024"

[dependencies]
product-pipeline-common = { workspace = true }
product = { workspace = true, features = ["dynamodb"] }
common = { workspace = true, features = ["dynamodb", "event_bridge"] }
async-trait = { workspace = true }
tracing = { workspace = true }
mockall = { workspace = true }
aws-config = { workspace = true }
aws-sdk-sqs = { workspace = true }
tokio = { workspace = true, features = ["time", "macros", "rt-multi-thread"] }
serde = { workspace = true }
serde_json = { workspace = true }
pyo3 = { workspace = true, features = ["auto-initialize"] }
pyo3-ffi = { workspace = true }
itertools = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

[dev-dependencies]
product-pipeline-common = { workspace = true, features = ["test-data"] }
product-pipeline-init = { workspace = true }
product-pipeline-translate = { workspace = true }
product-pipeline-embed-text = { workspace = true }
product-pipeline-complete = { workspace = true }
fake = { workspace = true }
rstest = { workspace = true }
serial_test = { workspace = true }
test-api = { workspace = true, features = ["sqs", "dynamodb", "opensearch"] }
time = { workspace = true }
uuid = { workspace = true }
serde_dynamo = { workspace = true }
aws_lambda_events = { workspace = true, features = ["sqs"] }
