[package]
name = "product-personalization"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["api"] }
product = { workspace = true, features = ["dynamodb", "service"] }
product-watchlist = { workspace = true, features = ["data", "dynamodb", "service"] }
notification = { workspace = true, features = ["service"] }
search-filter = { workspace = true, features = ["dynamodb"] }
user = { workspace = true, features = ["dynamodb", "service"] }
async-trait = { workspace = true }
futures = { workspace = true }
mockall = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true, optional = true }
uuid = { workspace = true }
time = { workspace = true }
url = { workspace = true }

[dev-dependencies]
product-personalization = { workspace = true }
notification = { workspace = true, features = ["test-data"] }
search-filter = { workspace = true, features = ["test-data"] }
user = { workspace = true, features = ["test-data"] }
time = { workspace = true }
fake = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
