[package]
name = "product-personalization"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["api"] }
product = { workspace = true, features = ["dynamodb", "service"] }
product-watchlist = { workspace = true, features = ["data", "dynamodb", "service"] }
user = { workspace = true, features = ["dynamodb", "service"] }
async-trait = { workspace = true }
mockall = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
product-personalization = { workspace = true }
time = { workspace = true }
fake = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
