[package]
name = "item"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true, features = ["local-offset", "macros", "formatting"] }
async-trait = { workspace = true }
mockall = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true }

# Optional
field = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
fake = { workspace = true, optional = true }
aws-sdk-dynamodb = { workspace = true, optional = true }
aws-sdk-sqs = { workspace = true, optional = true }
opensearch = { workspace = true, optional = true }
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+1"], optional = true }
itertools = { workspace = true, optional = true }
user = { workspace = true, optional = true, features = ["dynamodb"] }
shop = { workspace = true, optional = true }
strum = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
aws-config = { workspace = true }
item = { workspace = true, features = ["full"] }
test-api = { workspace = true, features = ["dynamodb", "opensearch", "sqs"] }
serial_test = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[features]
default = []
data = ["common/api"]
dynamodb = [
    "aws-sdk-dynamodb",
    "serde_dynamo",
    "common/dynamodb",
    "tracing",
    "field"
]
opensearch = ["dynamodb", "dep:opensearch", "tracing", "strum", "common/opensearch"]
sqs = ["aws-sdk-sqs", "common/sqs"]
service = ["itertools", "shop", "shop/dynamodb", "tokio", "tokio/time"]
watchlist = ["dynamodb", "service", "user", "user/dynamodb"]
test-data = ["fake", "common/test-data", "shop/test-data", "user/test-data"]
full = ["data", "dynamodb", "opensearch", "service", "watchlist", "sqs", "test-data"]
