[package]
name = "product-lambda-ingest-partner-products"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-sqs = { workspace = true }
aws_lambda_events = { workspace = true, features = ["sqs"] }
common = { workspace = true, features = ["sqs", "api", "opensearch"] }
geo = { workspace = true }
itertools = { workspace = true }
indexmap = { workspace = true }
lambda_runtime = { workspace = true }
llm = { workspace = true, features = ["google"] }
mockall = { workspace = true }
opensearch = { workspace = true }
product = { workspace = true, features = ["data", "dynamodb", "service"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
shop = { workspace = true, features = ["dynamodb", "service", "seller"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
time = { workspace = true }
url = { workspace = true }

[dev-dependencies]
common = { workspace = true, features = ["test-data"] }
fake = { workspace = true }
product = { workspace = true, features = ["test-data", "full"] }
shop = { workspace = true, features = ["test-data", "seller"] }
test-api = { workspace = true, features = ["dynamodb"] }
serial_test = { workspace = true }
