[package]
name = "shop-api-search"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["api"] }
shop-core = { workspace = true }
shop-service = { workspace = true, features = ["opensearch", "api"] }
shop-opensearch = { workspace = true }
shop-data = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["macros"] }
aws_lambda_events = { workspace = true, features = ["apigw"] }
lambda_runtime = { workspace = true }
aws-config = { workspace = true }
opensearch = { workspace = true }
serde_json = { workspace = true }
http = { workspace = true }

[dev-dependencies]
test-api = { workspace = true, features = ["api-gateway", "opensearch"] }
rstest = { workspace = true }
serial_test = { workspace = true }
http = { workspace = true }
fake = { workspace = true }
shop-core = { workspace = true, features = ["test-data"] }
shop-data = { workspace = true, features = ["test-data"] }
shop-opensearch = { workspace = true, features = ["test-data"] }
