[package]
name = "user"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
serde = { workspace = true }
serde-email = { workspace = true }
serde_fields = { workspace = true }
time = { workspace = true }
async-trait = { workspace = true }
mockall = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

# Optional
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+1"], optional = true }
tracing = { workspace = true, optional = true }
aws-sdk-dynamodb = { workspace = true, optional = true }
aws-sdk-cognitoidentityprovider = { workspace = true, optional = true }
tokio = { workspace = true, features = ["time"], optional = true }
fake = { workspace = true, optional = true }
reqwest = { workspace = true, features = ["json"], optional = true }
serde_json = { workspace = true, optional = true }

[dev-dependencies]
user = { workspace = true, features = ["full"] }
test-api = { workspace = true, features = ["dynamodb"] }
serial_test = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
wiremock = "0.6"

[features]
default = []
data = ["common/api"]
dynamodb = ["aws-sdk-dynamodb", "serde_dynamo", "serde_dynamo/aws-sdk-dynamodb+1", "tracing", "common/dynamodb"]
cognito = ["aws-sdk-cognitoidentityprovider"]
zoho = ["reqwest", "serde_json", "tracing", "tokio", "tokio/sync"]
service = ["dynamodb", "tokio"]
test-data = ["fake", "common/test-data"]
full = ["data", "test-data", "dynamodb", "service", "cognito", "zoho"]
