[package]
name = "search-filter-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
common = { workspace = true, features = ["postgres"] }
product-core = { workspace = true }
search-filter-core = { workspace = true }
search-filter-service = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
test-api = { workspace = true, features = ["postgres"] }
tokio = { workspace = true, features = ["macros", "rt"] }
