[package]
name = "watchlist-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["postgres"] }
application = { workspace = true }
user-core = { workspace = true }
async-trait = { workspace = true }
platform-postgres = { workspace = true }
product-core = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
product-service = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
watchlist-core = { workspace = true }
watchlist-service = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
test-api = { workspace = true, features = ["postgres"] }
tokio = { workspace = true, features = ["macros", "rt"] }
