[package]
name = "product-api"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["api", "opensearch"] }
product = { workspace = true, features = ["data", "service", "dynamodb", "opensearch", "sqs"] }
embedding = { workspace = true }
google-cloud-auth = { workspace = true }
product-watchlist = { workspace = true, features = ["data", "service", "dynamodb"] }
product-personalization = { workspace = true }
notification = { workspace = true, features = ["service"] }
user = { workspace = true, features = ["dynamodb", "service", "data"] }
cognito = { workspace = true }
search-filter = { workspace = true, features = ["dynamodb"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["macros"] }
aws_lambda_events = { workspace = true, features = ["apigw"] }
lambda_runtime = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
serde_json = { workspace = true }
serde_qs = { workspace = true }
http = { workspace = true }
url = { workspace = true }
time = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
product = { workspace = true, features = ["test-data"] }
product-watchlist = { workspace = true, features = ["test-data"] }
notification = { workspace = true, features = ["test-data"] }
user = { workspace = true, features = ["test-data"] }
shop = { workspace = true, features = ["data"] }
test-api = { workspace = true, features = ["api-gateway", "dynamodb", "opensearch", "sqs"] }
serial_test = { workspace = true }
rstest = { workspace = true }
fake = { workspace = true }
isocountry = { workspace = true }
geo = { workspace = true }
