#!/usr/bin/env python3
"""Generate Rust lookup tables offline from the immutable vendored release."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "reference/iso-codes-4.20.1"
HASHES = {
    "1": "f01b812b57fba9f31ff621bf33e7c7570a01964dbeb5be2167e94decf538c89f",
    "2": "78c90ef7fc25b5c2631aac5f089bc9ff6ec22c025c05b6ddbc087a1f1be2e46a",
    "3": "eb92d1cce3e352559f610e60e2acb23687eb1cf07b23675fb112863a5741a6fa",
}
records = {}
for part, digest in HASHES.items():
    raw = (SOURCE / f"iso_3166-{part}.json").read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest:
        raise ValueError(f"Reference part {part} changed; retain the old release")
    records[part] = json.loads(raw)[f"3166-{part}"]

countries = sorted(row["alpha_2"] for row in records["1"])
subdivisions = sorted(row["code"] for row in records["2"])
if len(countries) != 249 or len(countries) != len(set(countries)):
    raise ValueError("Country release is incomplete or contains duplicate codes")
if len(subdivisions) != len(set(subdivisions)):
    raise ValueError("Subdivision release contains duplicate codes")
if not all(re.fullmatch(r"[A-Z]{2}-[A-Z0-9]{1,3}", code) for code in subdivisions):
    raise ValueError("Subdivision release contains malformed codes")
if not all(code[:2] in countries for code in subdivisions):
    raise ValueError("Subdivision release contains an unrecognized country")
former_codes = [row["alpha_4"] for row in records["3"]]
if len(former_codes) != len(set(former_codes)):
    raise ValueError("Former-country release contains duplicate codes")

lines = [
    "// Generated by scripts/generate_reference.py; do not edit.",
    "// SPDX-FileCopyrightText: 2016 Dr. Tobias Quathamer <toddy@debian.org>",
    "// SPDX-License-Identifier: LGPL-2.1-or-later",
]
for name, values in [("COUNTRIES", countries), ("SUBDIVISIONS", subdivisions)]:
    lines.append(f"pub(super) const {name}: &[&str] = &[")
    lines.extend(f"    {json.dumps(value)}," for value in values)
    lines.append("];")

lines.append("pub(super) const FORMER_COUNTRIES: &[super::FormerCountry] = &[")
for row in sorted(records["3"], key=lambda row: row["alpha_4"]):
    lines.append("    super::FormerCountry {")
    for field, source in [("alpha4", "alpha_4"), ("former_alpha2", "alpha_2"),
                          ("name", "name"), ("withdrawal_date", "withdrawal_date")]:
        lines.append(f"        {field}: {json.dumps(row[source], ensure_ascii=False)},")
    lines.append("    },")
lines.append("];")

output = ROOT / "src/reference_codes.rs"
generated = subprocess.run(
    ["rustfmt", "--edition", "2024", "--emit", "stdout"],
    input="\n".join(lines) + "\n",
    capture_output=True,
    text=True,
    check=True,
).stdout
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true", help="Verify tables without writing files")
if parser.parse_args().check:
    if output.read_bytes() != generated.encode("utf-8"):
        raise ValueError("Reference tables are stale; run scripts/generate_reference.py")
else:
    output.write_bytes(generated.encode("utf-8"))
