[package]
name = "product-api-partner"
version = "0.1.0"
edition = "2024"

[dependencies]
geo = { workspace = true }
common = { workspace = true, features = ["api", "opensearch"] }
product = { workspace = true, features = ["data", "service", "dynamodb"] }
product-lambda-ingest-partner-products = { workspace = true }
shop = { workspace = true, features = ["dynamodb", "api", "service", "seller"] }
cognito = { workspace = true }
user = { workspace = true, features = ["dynamodb", "service", "data", "authenticator"] }
llm = { workspace = true, features = ["google"] }

tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["macros"] }
aws_lambda_events = { workspace = true, features = ["apigw"] }
lambda_runtime = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-sqs = { workspace = true }
opensearch = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

http = { workspace = true }
url = { workspace = true }
time = { workspace = true }

[dev-dependencies]
user = { workspace = true, features = ["test-data"] }
common = { workspace = true, features = ["test-data"] }
product = { workspace = true, features = ["test-data"] }

shop = { workspace = true, features = ["test-data", "seller"] }
test-api = { workspace = true, features = ["api-gateway", "dynamodb", "sqs"] }
rstest = { workspace = true }
fake = { workspace = true }
serial_test = { workspace = true }
