[package]
name = "partner-shop-application-api"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["api"] }
partner-shop-application = { workspace = true, features = ["data", "service"] }
shop = { workspace = true, features = ["data", "service", "dynamodb"] }
user = { workspace = true, features = ["data", "service"] }
serde = { workspace = true }
serde_json = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-sfn = { workspace = true }
aws_lambda_events = { workspace = true, features = ["apigw"] }
lambda_runtime = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
http = { workspace = true }
time = { workspace = true }

[dev-dependencies]
partner-shop-application = { workspace = true, features = ["test-data"] }
common = { workspace = true, features = ["test-data"] }
user = { workspace = true, features = ["test-data"] }
test-api = { workspace = true, features = ["api-gateway", "dynamodb"] }
serial_test = { workspace = true }
fake = { workspace = true }
