[package]
name = "product-pipeline-complete"
version = "0.1.0"
edition = "2024"

[dependencies]
product-pipeline-common = { workspace = true }
product = { workspace = true, features = ["service", "opensearch", "dynamodb"] }
common = { workspace = true, features = ["dynamodb", "event_bridge", "opensearch", "api"] }
async-trait = { workspace = true }
opensearch = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
mockall = { workspace = true }
aws-config = { workspace = true }
aws-sdk-sqs = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
tokio = { workspace = true, features = ["time", "macros", "rt-multi-thread"] }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
fake = { workspace = true }
product-pipeline-common = { workspace = true, features = ["test-data"] }
product = { workspace = true, features = ["test-data"] }
rstest = { workspace = true }
serial_test = { workspace = true }
test-api = { workspace = true, features = ["sqs"] }
