[package]
name = "product-watchlist"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
product = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_fields = { workspace = true }
time = { workspace = true, features = ["local-offset", "macros", "formatting"] }
async-trait = { workspace = true }
mockall = { workspace = true }
thiserror = { workspace = true }
user = { workspace = true, features = ["service", "data"] }

# Optional
tracing = { workspace = true, optional = true }
fake = { workspace = true, optional = true }
aws-sdk-dynamodb = { workspace = true, optional = true }
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+1"], optional = true }
itertools = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
product-watchlist = { workspace = true, features = ["full"] }
product = { workspace = true, features = ["test-data"] }
user = { workspace = true, features = ["test-data"] }
test-api = { workspace = true, features = ["dynamodb"] }
serial_test = { workspace = true }
rstest = { workspace = true }
fake = { workspace = true }

[features]
default = []
data = ["common/api", "product/data"]
dynamodb = ["aws-sdk-dynamodb", "serde_dynamo", "common/dynamodb", "tracing", "product/dynamodb"]
service = ["dynamodb", "itertools", "tokio", "tokio/time", "product/service"]
test-data = ["fake", "common/test-data", "product/test-data"]
full = ["data", "dynamodb", "service", "test-data"]
