[package]
name = "geo"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
isocountry = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
mockall = { workspace = true, optional = true }
fake = { workspace = true, optional = true }

[dev-dependencies]
geo = { workspace = true, features = ["full"] }
tokio = { workspace = true, features = ["macros", "rt"] }
wiremock = "0.6"

[features]
default = []
data = []
service = ["mockall"]
test-data = ["fake"]
full = ["data", "service", "test-data"]
