[package]
name = "backend-cleanup-lambda"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_runtime = { workspace = true }
oauth-postgres = { workspace = true }
oauth-service = { workspace = true }
platform-lambda-bootstrap = { workspace = true }
platform-observability = { workspace = true }
platform-postgres-secretsmanager = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
