[package]
name = "search-filter-core"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
domain-primitives = { workspace = true }
fxrate-core = { workspace = true }
product-core = { workspace = true }
fake = { workspace = true, optional = true }
serde_fields = { workspace = true }

[dev-dependencies]
localization = { workspace = true }
money = { workspace = true }

[features]
default = []
test-data = ["fake", "common/test-data", "domain-primitives/test-data", "fxrate-core/test-data", "product-core/test-data"]
