[package]
name = "notification"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
serde = { workspace = true }
serde-email = { workspace = true }
serde_fields = { workspace = true }
time = { workspace = true }
async-trait = { workspace = true }
mockall = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

# Optional
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+1"], optional = true }
tracing = { workspace = true, optional = true }
aws-sdk-dynamodb = { workspace = true, optional = true }
fake = { workspace = true, optional = true }
product = { workspace = true, optional = true }
user = { workspace = true, optional = true }
aws-sdk-sesv2 = { workspace = true, optional = true }
aws-sdk-s3 = { workspace = true, optional = true }
handlebars = { workspace = true, optional = true }
once_cell = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, features = ["sync"] }

[dev-dependencies]
notification = { workspace = true, features = ["full"] }
test-api = { workspace = true, features = ["dynamodb"] }
serial_test = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[features]
default = []
data = ["common/api"]
dynamodb = ["aws-sdk-dynamodb", "serde_dynamo", "serde_dynamo/aws-sdk-dynamodb+1", "tracing", "common/dynamodb", "product", "product/dynamodb"]
service = [
    "dynamodb",
    "user", "user/service",
    "aws-sdk-sesv2",
    "aws-sdk-s3",
    "handlebars",
    "once_cell",
    "serde_json",
    "tokio", "tokio/sync",
]
test-data = ["fake", "common/test-data", "product", "product/test-data", "user/test-data"]
full = ["data", "test-data", "dynamodb", "service"]
