[package]
name = "cognito"
version = "0.1.0"
edition = "2024"

[dependencies]
user-core = { workspace = true }
uuid = { workspace = true }
http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

async-trait = { workspace = true }
mockall = { workspace = true }
jsonwebtokens = { workspace = true }
jsonwebtokens-cognito = { workspace = true }
openssl = { workspace = true, features = ["vendored"] } # we unfortunately need this as crates "jsonwebtokens*" cannot do rust-tls
reqwest = { workspace = true, features = ["json"] }
