[package]
name = "product-lambda-ingest-events-dynamodb"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["dynamodb"] }
product = { workspace = true, features = ["dynamodb"] }
lambda_runtime = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws_lambda_events = { workspace = true, features = ["sqs"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing-subscriber = { workspace = true, features = ["json"] }
tracing = { workspace = true }

[dev-dependencies]
product = { workspace = true, features = ["test-data"] }
rstest = { workspace = true }
fake = { workspace = true }
uuid = { workspace = true }
serde_dynamo = { workspace = true }
