[package]
name = "newsletter-api"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["api"] }
cognito = { workspace = true }
user = { workspace = true, features = ["dynamodb", "service"] }
serde = { workspace = true }
serde-email = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["macros", "sync"] }
aws_lambda_events = { workspace = true, features = ["apigw"] }
lambda_runtime = { workspace = true }
aws-config = { workspace = true }
http = { workspace = true }
time = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
mockall = { workspace = true }

[dev-dependencies]
user = { workspace = true, features = ["test-data"] }
common = { workspace = true, features = ["test-data"] }
test-api = { workspace = true, features = ["api-gateway"] }
fake = { workspace = true }
wiremock = "0.6"
