[package]
name = "product-lambda-delete-product"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["dynamodb", "event_bridge", "opensearch"] }
product = { workspace = true, features = ["dynamodb", "opensearch"] }
product-watchlist = { workspace = true, features = ["service"] }
search-filter = { workspace = true, features = ["dynamodb"] }
lambda_runtime = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws_lambda_events = { workspace = true, features = ["sqs", "dynamodb", "eventbridge"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing-subscriber = { workspace = true, features = ["json"] }
tracing = { workspace = true }
opensearch = { workspace = true }
mockall = { workspace = true }

[dev-dependencies]
product = { workspace = true, features = ["test-data"] }
product-watchlist = { workspace = true, features = ["test-data"] }
search-filter = { workspace = true, features = ["test-data"] }
fake = { workspace = true }
