[package]
name = "fxrate-core"
version = "0.1.0"
edition = "2024"

[dependencies]
domain-primitives = { workspace = true }
money = { workspace = true }
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

# Optional
fake = { workspace = true, optional = true }

[dev-dependencies]
rstest = { workspace = true }
serde_json = { workspace = true }

[features]
default = []
test-data = ["dep:fake", "domain-primitives/test-data"]
