[package]
name = "item-api"
version = "0.1.0"
edition = "2024"

[dependencies]
item-api-get-item = { workspace = true }
item-api-put-items = { workspace = true }
item-api-simple-search = { workspace = true }
item-api-complex-search = { workspace = true }
item-api-watchlist-get = { workspace = true }
item-api-watchlist-post = { workspace = true }
item-api-watchlist-delete = { workspace = true }
