[package]
name = "acceptance-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["opensearch"] }
test-api = { workspace = true, features = ["cloudformation", "dynamodb", "opensearch", "sqs", "api-gateway", "eventbridge"] }
aws-tests-common = { workspace = true }
base64 = { workspace = true }
tokio = { workspace = true, features = ["full"] }
product = { workspace = true, features = ["full"] }
product-watchlist = { workspace = true, features = ["full"] }
notification = { workspace = true, features = ["service", "dynamodb", "data", "test-data"] }
partner-shop-application = { workspace = true, features = ["data", "service", "dynamodb", "test-data"] }
shop = { workspace = true, features = ["full"] }
user = { workspace = true, features = ["full"] }
search-filter = { workspace = true, features = ["full"] }
search-filter-periodic-match = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-sqs = { workspace = true }
aws-sdk-eventbridge = { workspace = true }
aws-sdk-cloudwatchlogs = { workspace = true }
opensearch = { workspace = true }
openssl = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
tracing-subscriber = { workspace = true, features = ["json"] }
tracing = { workspace = true }
aws-sdk-cognitoidentityprovider = { workspace = true }
fake = { workspace = true }
time = { workspace = true }
reqwest = { workspace = true, features = ["default", "json"] }

[dev-dependencies]
common = { workspace = true, features = ["test-data"] }
serial_test = { workspace = true }
http = { workspace = true }
product-watchlist-api = { workspace = true }
notification-api = { workspace = true }
oauth = { workspace = true }
search-filter-api = { workspace = true, features = ["test-data"] }
url = { workspace = true }
futures-util = { workspace = true }
time = { workspace = true }
