[package]
name = "notification-send"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["dynamodb", "event_bridge"] }
notification = { workspace = true, features = ["service"] }
user = { workspace = true, features = ["dynamodb", "service", "data"] }
lambda_runtime = { workspace = true }
aws-config = { workspace = true }
aws_lambda_events = { workspace = true, features = ["sqs", "dynamodb", "eventbridge"] }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-sesv2 = { workspace = true }
aws-sdk-s3 = { workspace = true }
serde_json = { workspace = true }
serde_dynamo = { workspace = true }
serde-email = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing-subscriber = { workspace = true, features = ["json"] }
tracing = { workspace = true }

[dev-dependencies]
notification = { workspace = true, features = ["test-data"] }
fake = { workspace = true }
rstest = { workspace = true }
serde = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
