[package]
name = "shopify-lambda"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
aws_lambda_events = { workspace = true, features = ["eventbridge", "sqs"] }
common = { workspace = true, features = ["postgres"] }
indexmap = { workspace = true }
lambda_runtime = { workspace = true }
product-core = { workspace = true }
product-postgres = { workspace = true }
product-service = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
shop-postgres = { workspace = true }
shop-service = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
url = { workspace = true }
html-to-markdown-rs = { workspace = true }

[dev-dependencies]
test-api = { workspace = true, features = ["postgres"] }
sqlx = { workspace = true }
serial_test = { workspace = true }
shop-core = { workspace = true }
common = { workspace = true, features = ["postgres"] }
uuid = { workspace = true }
