[package]
name = "shop-partner-service"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
common = { workspace = true }
geo = { workspace = true }
notification-core = { workspace = true }
notification-service = { workspace = true }
serde = { workspace = true }
serde-email = { workspace = true }
shop-core = { workspace = true }
shop-service = { workspace = true }
shop-partner-core = { workspace = true }
time = { workspace = true, features = ["local-offset", "macros", "formatting"] }
user-core = { workspace = true }
user-service = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

# Optional
fake = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
default = []
test-data = ["fake", "common/test-data", "shop-core/test-data", "shop-partner-core/test-data"]
