[package]
name = "mail-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde-email = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# Optional
tokio = { workspace = true, optional = true, features = ["sync"] }
aws-sdk-sesv2 = { workspace = true, optional = true }
aws-sdk-s3 = { workspace = true, optional = true }
aws-sdk-sqs = { workspace = true, optional = true }
handlebars = { workspace = true, optional = true }
once_cell = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
mockall = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }

[dev-dependencies]
aws-config = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
mail-core = { workspace = true, features = ["queue", "send"] }

[features]
default = []
queue = ["aws-sdk-sqs", "thiserror", "mockall", "async-trait"]
send = ["tokio", "tokio/sync", "aws-sdk-sesv2", "aws-sdk-s3", "handlebars", "once_cell", "thiserror", "mockall", "async-trait"]
