[package]
name = "search-filter"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
large-language-model = { workspace = true, optional = true }
geo = { workspace = true, features = ["data"] }
isocountry = { workspace = true }
time = { workspace = true, features = ["local-offset", "macros", "formatting"] }
thiserror = { workspace = true }
serde = { workspace = true }
serde_fields = { workspace = true }
uuid = { workspace = true, features = ["v7"] }
mockall = { workspace = true }
async-trait = { workspace = true }
user = { workspace = true, features = ["dynamodb", "service", "data"] }
serde_dynamo = { workspace = true, features = [ "aws-sdk-dynamodb+1" ] }

# Optional
fake = { workspace = true, optional = true }
product = { workspace = true, optional = true }
shop = { workspace = true, optional = true }
field = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
aws-sdk-dynamodb = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
opensearch = { workspace = true, optional = true }
embedding = { workspace = true, optional = true }
llm = { workspace = true, features = ["google", "rustls-tls"], optional = true }
reqwest = { workspace = true, optional = true }

[dev-dependencies]
search-filter = { workspace = true, features = ["full"] }
product = { workspace = true, features = ["full"] }
test-api = { workspace = true, features = ["dynamodb", "opensearch"] }
serial_test = { workspace = true }
serde_json = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
user = { workspace = true, features = ["full"] }

[features]
default = []
dynamodb = ["common/dynamodb", "product", "product/dynamodb", "shop/dynamodb", "field", "tracing", "aws-sdk-dynamodb", "serde_dynamo/aws-sdk-dynamodb+1"]
opensearch = ["common/opensearch", "dynamodb", "product/opensearch", "shop/opensearch", "serde_json", "dep:opensearch"]
service = ["common/dynamodb", "product", "product/opensearch", "shop", "user/service", "user/dynamodb", "embedding", "llm", "dep:large-language-model", "reqwest", "tracing", "serde_json"]
data = ["product", "product/data", "shop/data"]
test-data = ["fake", "common/test-data", "product/test-data", "shop/test-data", "user/test-data"]
full = ["dynamodb", "opensearch", "service", "data", "test-data"]
