[package]
name = "stripe-lambda"
version = "0.1.0"
edition = "2024"

[dependencies]
application = { workspace = true }
platform-observability = { workspace = true }
platform-postgres = { workspace = true }
tracing = { workspace = true }
user-core = { workspace = true }
user-service = { workspace = true }
user-postgres = { workspace = true }

tokio = { workspace = true, features = ["macros"] }
aws_lambda_events = { workspace = true, features = ["eventbridge"] }
lambda_runtime = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
serial_test = { workspace = true }
test-api = { workspace = true, features = ["postgres"] }
serde-email = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
