[package]
name = "product-pipeline-embed-text"
version = "0.1.0"
edition = "2024"

[dependencies]
product = { workspace = true, features = ["dynamodb", "service"] }
common = { workspace = true, features = ["dynamodb", "event_bridge"] }
fxrate = { workspace = true }
shop = { workspace = true, features = ["dynamodb", "service", "seller"] }
async-trait = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
mockall = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
lambda_runtime = { workspace = true }
aws_lambda_events = { workspace = true, features = [
    "sqs",
    "dynamodb",
    "eventbridge",
] }
tokio = { workspace = true, features = ["macros", "sync", "time"] }
lru = "0.16"
serde = { workspace = true }
serde_json = { workspace = true }
serde_dynamo = { workspace = true }
google-cloud-auth = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
url = { workspace = true }
base64 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
product = { workspace = true, features = ["test-data"] }
fake = { workspace = true }
rstest = { workspace = true }
uuid = { workspace = true }
time = { workspace = true }
test-api = { workspace = true, features = ["dynamodb"] }
serial_test = { workspace = true }
serde_dynamo = { workspace = true }

[[test]]
name = "integration"
path = "tests/lib.rs"
