[package]
name = "user-zoho"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
common = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
user-core = { workspace = true }
user-service = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
url = { workspace = true }
wiremock = "0.6"
