[package]
name = "search-filter-api-patch-search-filter"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["api"] }
search-filter-core = { workspace = true }
search-filter-service = { workspace = true, features = ["api"] }
search-filter-dynamodb = { workspace = true }
search-filter-data = { workspace = true }
item-data = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["macros"] }
aws_lambda_events = { workspace = true, features = ["apigw"] }
lambda_runtime = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
serde_json = { workspace = true }
http = { workspace = true }
time = { workspace = true }
serde = { workspace = true }

# Optional
fake = { workspace = true, optional = true }

[dev-dependencies]
test-api = { workspace = true, features = ["api-gateway", "dynamodb"] }
serial_test = { workspace = true }
rstest = { workspace = true }
time = { workspace = true }
http = { workspace = true }
url = { workspace = true }
search-filter-dynamodb = { workspace = true, features = ["test-data"] }
search-filter-data = { workspace = true, features = ["test-data"] }
search-filter-api-patch-search-filter = { workspace = true, features = ["test-data"] }

[features]
default = []
test-data = ["fake", "common/test-data", "search-filter-core/test-data", "item-data/test-data"]
