[package]
name = "search-filter-api-get-search-filter"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["api"] }
search-filter = { workspace = true, features = ["data", "service", "dynamodb"] }
product = { workspace = true, features = ["data"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["macros"] }
aws_lambda_events = { workspace = true, features = ["apigw"] }
lambda_runtime = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
serde_json = { workspace = true }
http = { workspace = true }

[dev-dependencies]
test-api = { workspace = true, features = ["api-gateway", "dynamodb"] }
serial_test = { workspace = true }
rstest = { workspace = true }
time = { workspace = true }
http = { workspace = true }
url = { workspace = true }
search-filter = { workspace = true, features = ["test-data"] }
fake = { workspace = true }
