[package]
name = "shop"
version = "0.1.0"
edition = "2024"

## core
[dependencies]
common = { workspace = true }
time = { workspace = true, features = ["local-offset", "macros", "formatting"] }
url = { workspace = true, features = ["serde"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_fields = { workspace = true }
async-trait = { workspace = true }
mockall = { workspace = true }
thiserror = { workspace = true }
prefixed-api-key = { workspace = true, features = ["sha2"] }

# Optional
fake = { workspace = true, optional = true }
field = { workspace = true, optional = true }
aws-sdk-dynamodb = { workspace = true, optional = true }
aws_lambda_events = { workspace = true, features = ["apigw"], optional = true }
http = { workspace = true, optional = true }
serde_dynamo = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
opensearch = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
strum = { workspace = true, optional = true }
strum_macros = { workspace = true, optional = true }
llm = { workspace = true, optional = true }

[dev-dependencies]
shop = { workspace = true, features = ["full", "seller"] }
aws-config = { workspace = true }
test-api = { workspace = true, features = ["dynamodb", "opensearch"] }
serial_test = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros", "time"] }

[features]
default = []
api = ["data", "aws_lambda_events", "http"]
data = ["common/api"]
dynamodb = ["common/dynamodb", "field", "aws-sdk-dynamodb", "serde_dynamo", "tracing", "strum"]
opensearch = ["common/opensearch", "dep:opensearch", "tracing", "strum", "strum_macros"]
service = ["tokio", "tokio/time"]
test-data = ["fake", "common/test-data"]
llm = ["dep:llm"]
seller = ["dynamodb", "opensearch", "service", "llm"]
full = ["api", "data", "dynamodb", "opensearch", "service", "test-data", "seller"]
