[package]
name = "shop-partner-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
shop-core = { workspace = true }
user-core = { workspace = true }
uuid = { workspace = true }

thiserror = { workspace = true }

# Optional
fake = { workspace = true, optional = true }

[features]
default = []
test-data = ["fake", "shop-core/test-data", "user-core/test-data"]
