[package]
name = "aura-scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
scraper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
schemars = { workspace = true }
async-trait = { workspace = true }
mockall = { workspace = true }
llm = { workspace = true }
kuchiki = { workspace = true }
reqwest = { workspace = true, features = ["default", "json"] }
tokio = { workspace = true, features = ["macros"] }

# Optional
fake = { workspace = true, optional = true }

[dev-dependencies]
rstest = { workspace = true }

[features]
default = []
test-data = ["common/test-data", "fake"]
