[package]
name = "aura-scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
product = { workspace = true, features = ["dynamodb", "service", "data"] }
shop = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true, features = ["postgres"] }
scraper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
schemars = { workspace = true }
async-trait = { workspace = true }
mockall = { workspace = true }
llm = { workspace = true }
kuchiki = { workspace = true }
reqwest = { workspace = true, features = ["default", "json"] }
tokio = { workspace = true, features = ["macros"] }
time = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
lingua = { workspace = true }
dotenvy = "0.15"

# Optional
fake = { workspace = true, optional = true }

[dev-dependencies]
aura-scraper = { workspace = true, features = ["test-data"] }
rstest = { workspace = true }
fake = { workspace = true }
serial_test = { workspace = true }
test-api = { workspace = true, features = ["rds"] }
tokio = { workspace = true, features = ["macros", "time"] }

[[bin]]
name = "demo"
path = "src/demo.rs"

[features]
default = []
test-data = ["common/test-data", "fake"]

[target.'cfg(not(target_env = "msvc"))'.dependencies]
libc = { workspace = true }
