[package]
name = "oauth-core"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { workspace = true }
fake = { workspace = true, optional = true }
credential-core = { workspace = true }
domain-primitives = { workspace = true }
serde = { workspace = true }
time = { workspace = true, features = ["serde"] }
url = { workspace = true, features = ["serde"] }
user-core = { workspace = true }

[features]
default = []
test-data = ["fake", "credential-core/test-data", "user-core/test-data"]
