[package]
name = "database-migration-lambda"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_runtime = { workspace = true }
platform-lambda-bootstrap = { workspace = true }
platform-observability = { workspace = true }
platform-postgres = { workspace = true }
platform-postgres-secretsmanager = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }

[dev-dependencies]
test-api = { workspace = true, features = ["postgres"] }
