[package]
name = "shop-core"
version = "0.1.0"
edition = "2024"

[dependencies]
domain-primitives = { workspace = true }
localization = { workspace = true }
money = { workspace = true }
geo = { workspace = true }
isocountry = { workspace = true }
percent-encoding = { workspace = true }
serde = { workspace = true }
serde-email = { workspace = true }
slug = { workspace = true }
strum = { workspace = true }
time = { workspace = true, features = ["local-offset", "macros", "formatting"] }
thiserror = { workspace = true }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4"] }

# Optional
fake = { workspace = true, optional = true }

[features]
default = []
test-data = ["fake", "domain-primitives/test-data", "geo/test-data", "localization/test-data", "money/test-data"]
