[package]
name = "webhook-api"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-sqs = { workspace = true }
aws_lambda_events = { workspace = true, features = ["apigw"] }
base64 = { workspace = true }
common = { workspace = true, features = ["api", "opensearch"] }
geo = { workspace = true }
lambda_runtime = { workspace = true }
llm = { workspace = true, features = ["google"] }
opensearch = { workspace = true }
openssl = { workspace = true, features = ["vendored"] } # we unfortunately need this as crates "jsonwebtokens*" cannot do rust-tls
product = { workspace = true, features = ["dynamodb", "service"] }
product-lambda-ingest-partner-products = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
shop = { workspace = true, features = ["dynamodb", "api", "service", "seller"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
url = { workspace = true }
cognito = { workspace = true }
user = { workspace = true, features = ["dynamodb", "service", "data", "authenticator"] }
html-to-markdown-rs = { workspace = true }

[dev-dependencies]
common = { workspace = true, features = ["test-data"] }
fake = { workspace = true }
http = { workspace = true }
product = { workspace = true, features = ["test-data"] }
rstest = { workspace = true }
serial_test = { workspace = true }
shop = { workspace = true, features = ["test-data", "seller"] }
test-api = { workspace = true, features = ["api-gateway", "dynamodb", "sqs"] }
user = { workspace = true, features = ["test-data"] }
