use crawler::scraper::candidate_service::{
    ProductListingSnapshot, ScraperCandidateService, ScraperCandidateServiceImpl,
};
use crawler::spider::candidate_service::{SpiderCandidateService, SpiderCandidateServiceImpl};
use crawler::spider::classification::url_metadata::{UrlClass, UrlState};
use crawler::spider::classification::url_metadata_repository::{
    UrlMetadataRepository, UrlMetadataRepositoryImpl,
};
use std::collections::HashMap;
use test_api::*;

const POSTGRES: Postgres = Postgres::new("src/crawler/migrations");

fn minimal_snapshot(url: &str) -> ProductListingSnapshot {
    ProductListingSnapshot {
        price: None,
        price_estimate_min: None,
        price_estimate_max: None,
        url: url.to_string(),
        images_hash: "0".repeat(64),
        auction_start: None,
        auction_end: None,
        state: "AVAILABLE".to_string(),
    }
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/// Inserts a shop + its first domain; returns the generated domain_id.
async fn insert_shop_with_domain(
    pool: &sqlx::PgPool,
    shop_id_uuid: uuid::Uuid,
    domain: &str,
) -> uuid::Uuid {
    sqlx::query(
        "INSERT INTO shops (shop_id, shop_name, shop_type, created, updated) \
         VALUES ($1, $2, $3, NOW(), NOW())",
    )
    .bind(shop_id_uuid)
    .bind("Test Shop")
    .bind("COMMERCIAL_DEALER")
    .execute(pool)
    .await
    .unwrap();

    insert_domain_for_shop(pool, shop_id_uuid, domain).await
}

/// Inserts an additional domain row for an already-existing shop.
async fn insert_domain_for_shop(
    pool: &sqlx::PgPool,
    shop_id_uuid: uuid::Uuid,
    domain: &str,
) -> uuid::Uuid {
    let row: (uuid::Uuid,) = sqlx::query_as(
        "INSERT INTO shop_domains (shop_id, shop_domain) VALUES ($1, $2) RETURNING domain_id",
    )
    .bind(shop_id_uuid)
    .bind(domain)
    .fetch_one(pool)
    .await
    .unwrap();

    row.0
}

// ============================================================================
// SPIDER CANDIDATE SERVICE
// ============================================================================

// ---------------------------------------------------------------------------
// get_candidates — no eligible shops returns empty vec
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_return_empty_when_no_eligible_candidates_exist() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let candidates = service.get_candidates(10, &[]).await.unwrap();

    assert!(
        candidates.is_empty(),
        "expected no candidates for a fresh schema"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — newly-inserted domain (last_crawled IS NULL) is returned
//                  and carries the correct domain_id
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_return_candidate_with_correct_domain_id_when_never_crawled() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id =
        insert_shop_with_domain(&pool, shop_id_uuid, "spider-never-crawled.example.com").await;

    let candidates = service.get_candidates(10, &[]).await.unwrap();

    assert_eq!(candidates.len(), 1);
    assert_eq!(
        candidates[0].domain_id, domain_id,
        "candidate must carry the domain_id generated by shop_domains"
    );
    assert_eq!(
        candidates[0].shop_domain,
        "spider-never-crawled.example.com"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — domain crawled recently is NOT returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_not_return_candidate_when_recently_crawled() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "spider-recent.example.com").await;

    sqlx::query("UPDATE shop_domains SET last_crawled = NOW() WHERE domain_id = $1")
        .bind(domain_id)
        .execute(&pool)
        .await
        .unwrap();

    let candidates = service.get_candidates(10, &[]).await.unwrap();

    assert!(
        !candidates.iter().any(|c| c.domain_id == domain_id),
        "a domain crawled just now should not be returned as a candidate"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — domain crawled more than 7 days ago IS returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_return_candidate_when_crawled_more_than_7_days_ago() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "spider-stale.example.com").await;

    sqlx::query(
        "UPDATE shop_domains SET last_crawled = NOW() - INTERVAL '8 days' WHERE domain_id = $1",
    )
    .bind(domain_id)
    .execute(&pool)
    .await
    .unwrap();

    let candidates = service.get_candidates(10, &[]).await.unwrap();

    assert!(
        candidates.iter().any(|c| c.domain_id == domain_id),
        "stale domain should be returned with its domain_id"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — inactive shops are excluded
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_not_return_candidate_when_shop_is_inactive() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id =
        insert_shop_with_domain(&pool, shop_id_uuid, "spider-inactive.example.com").await;

    sqlx::query("UPDATE shops SET active = FALSE WHERE shop_id = $1")
        .bind(shop_id_uuid)
        .execute(&pool)
        .await
        .unwrap();

    let candidates = service.get_candidates(10, &[]).await.unwrap();

    assert!(
        !candidates.iter().any(|c| c.domain_id == domain_id),
        "candidates for inactive shops should be excluded"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — limit is respected
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_respect_limit_when_multiple_candidates_exist() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    for i in 0..3u32 {
        let shop_id_uuid = uuid::Uuid::new_v4();
        insert_shop_with_domain(
            &pool,
            shop_id_uuid,
            &format!("spider-limit-{}.example.com", i),
        )
        .await;
    }

    let candidates = service.get_candidates(2, &[]).await.unwrap();

    assert_eq!(
        candidates.len(),
        2,
        "get_candidates(2) should return at most 2 results"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — multiple domains on the same shop are each returned
//                  with their own domain_id
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_return_each_domain_separately_for_shop_with_multiple_domains() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    sqlx::query(
        "INSERT INTO shops (shop_id, shop_name, shop_type, created, updated) \
         VALUES ($1, $2, $3, NOW(), NOW())",
    )
    .bind(shop_id_uuid)
    .bind("Test Shop")
    .bind("COMMERCIAL_DEALER")
    .execute(&pool)
    .await
    .unwrap();

    let domain_id_a =
        insert_domain_for_shop(&pool, shop_id_uuid, "spider-multi-a.example.com").await;
    let domain_id_b =
        insert_domain_for_shop(&pool, shop_id_uuid, "spider-multi-b.example.com").await;

    let candidates = service.get_candidates(10, &[]).await.unwrap();

    let ids: Vec<uuid::Uuid> = candidates.iter().map(|c| c.domain_id).collect();
    assert!(ids.contains(&domain_id_a), "domain_id_a should be present");
    assert!(ids.contains(&domain_id_b), "domain_id_b should be present");
}

// ---------------------------------------------------------------------------
// get_candidates — shop_id on the candidate matches the owning shop
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_return_correct_shop_id_on_candidate() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "spider-shopid.example.com").await;

    let candidates = service.get_candidates(10, &[]).await.unwrap();

    let candidate = candidates
        .iter()
        .find(|c| c.domain_id == domain_id)
        .expect("candidate for the inserted domain should be present");

    let candidate_shop_uuid: uuid::Uuid = candidate.shop_id.into();
    assert_eq!(
        candidate_shop_uuid, shop_id_uuid,
        "candidate.shop_id must match the owning shop"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — failure metadata is included for retry policy decisions
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_return_crawl_failure_metadata_on_candidate() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id =
        insert_shop_with_domain(&pool, shop_id_uuid, "spider-failure-meta.example.com").await;

    sqlx::query(
        "UPDATE shop_domains
         SET crawl_failure_count = 2,
             last_crawl_error_kind = 'InsufficientInferenceSample'
         WHERE domain_id = $1",
    )
    .bind(domain_id)
    .execute(&pool)
    .await
    .unwrap();

    let candidates = service.get_candidates(10, &[]).await.unwrap();
    let candidate = candidates
        .iter()
        .find(|c| c.domain_id == domain_id)
        .expect("candidate for the inserted domain should be present");

    assert_eq!(candidate.crawl_failure_count, 2);
    assert_eq!(
        candidate.last_crawl_error_kind.as_deref(),
        Some("InsufficientInferenceSample")
    );
}

// ---------------------------------------------------------------------------
// mark_crawl_failure — stores the caller-provided consecutive count and retry
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_mark_crawl_failure_should_store_count_kind_and_next_crawl_at() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id =
        insert_shop_with_domain(&pool, shop_id_uuid, "spider-mark-failure.example.com").await;
    let next_crawl_at = time::OffsetDateTime::now_utc() + time::Duration::hours(6);

    service
        .mark_crawl_failure(&domain_id, "InsufficientInferenceSample", 3, next_crawl_at)
        .await
        .unwrap();

    let row: (i32, Option<String>, Option<time::OffsetDateTime>) = sqlx::query_as(
        "SELECT crawl_failure_count, last_crawl_error_kind, next_crawl_at
         FROM shop_domains
         WHERE domain_id = $1",
    )
    .bind(domain_id)
    .fetch_one(&pool)
    .await
    .unwrap();

    assert_eq!(row.0, 3);
    assert_eq!(row.1.as_deref(), Some("InsufficientInferenceSample"));
    let stored_next_crawl_at = row.2.expect("next_crawl_at should be stored");
    assert!(
        (stored_next_crawl_at - next_crawl_at).whole_seconds().abs() <= 1,
        "next_crawl_at should match the caller-provided timestamp"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — ordering: NULL last_crawled comes before stale domains
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_order_never_crawled_before_stale_crawled() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_stale = uuid::Uuid::new_v4();
    let shop_id_never = uuid::Uuid::new_v4();

    let domain_id_stale =
        insert_shop_with_domain(&pool, shop_id_stale, "spider-order-stale.example.com").await;
    let domain_id_never =
        insert_shop_with_domain(&pool, shop_id_never, "spider-order-never.example.com").await;

    sqlx::query(
        "UPDATE shop_domains SET last_crawled = NOW() - INTERVAL '10 days' WHERE domain_id = $1",
    )
    .bind(domain_id_stale)
    .execute(&pool)
    .await
    .unwrap();

    let candidates = service.get_candidates(100, &[]).await.unwrap();

    let pos_never = candidates
        .iter()
        .position(|c| c.domain_id == domain_id_never)
        .expect("never-crawled domain should be in candidates");
    let pos_stale = candidates
        .iter()
        .position(|c| c.domain_id == domain_id_stale)
        .expect("stale domain should be in candidates");

    assert!(
        pos_never < pos_stale,
        "never-crawled (pos {pos_never}) should come before stale (pos {pos_stale})"
    );
}

// ============================================================================
// SCRAPER CANDIDATE SERVICE
// ============================================================================

/// Helper: inserts a product URL into shop_urls for the given shop/domain.
async fn insert_product_url(
    pool: &sqlx::PgPool,
    shop_id_uuid: uuid::Uuid,
    domain_id: uuid::Uuid,
    url: &str,
) {
    let shop_id = shop_core::shop_id::ShopId::from(shop_id_uuid);
    let parsed = url::Url::parse(url).unwrap();
    let repo = UrlMetadataRepositoryImpl::new(pool.clone());
    repo.upsert_link(&shop_id, &domain_id, &parsed, &UrlClass::ProductListing)
        .await
        .unwrap();
}

// ---------------------------------------------------------------------------
// get_candidates — empty DB returns empty vec
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_return_empty_when_no_eligible_candidates_exist() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert!(
        candidates.is_empty(),
        "expected no candidates for a fresh schema"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — product URL never scraped IS returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_return_candidate_when_product_url_never_scraped() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "scraper-never.example.com").await;
    insert_product_url(
        &pool,
        shop_id_uuid,
        domain_id,
        "https://scraper-never.example.com/p/1",
    )
    .await;

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert!(
        candidates
            .iter()
            .any(|c| c.url.as_str() == "https://scraper-never.example.com/p/1"),
        "never-scraped product URL should be returned"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — URL scraped < 1 day ago is NOT returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_not_return_candidate_when_recently_scraped() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id =
        insert_shop_with_domain(&pool, shop_id_uuid, "scraper-recent.example.com").await;
    let url = "https://scraper-recent.example.com/p/1";
    let hash = "b".repeat(64);
    insert_product_url(&pool, shop_id_uuid, domain_id, url).await;

    // Mark as scraped just now
    sqlx::query("UPDATE shop_urls SET last_scraped = NOW(), last_scraped_hash = $1 WHERE url = $2")
        .bind(&hash)
        .bind(url)
        .execute(&pool)
        .await
        .unwrap();

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert!(
        !candidates.iter().any(|c| c.url.as_str() == url),
        "URL scraped just now should not be returned"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — URL scraped > 1 day ago IS returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_return_candidate_when_scraped_more_than_1_day_ago() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "scraper-stale.example.com").await;
    let url = "https://scraper-stale.example.com/p/1";
    insert_product_url(&pool, shop_id_uuid, domain_id, url).await;

    // Mark as scraped 2 days ago to isolate the time-based filter.
    let old_hash = "old_hash_differs";
    sqlx::query(
        "UPDATE shop_urls SET last_scraped = NOW() - INTERVAL '2 days', last_scraped_hash = $1 WHERE url = $2",
    )
    .bind(old_hash)
    .bind(url)
    .execute(&pool)
    .await
    .unwrap();

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert!(
        candidates.iter().any(|c| c.url.as_str() == url),
        "URL scraped 2 days ago should be returned"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — non-product URL class is NOT returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_not_return_candidate_when_url_class_is_not_product() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "scraper-class.example.com").await;

    // Insert as a category URL (not product)
    let shop_id = shop_core::shop_id::ShopId::from(shop_id_uuid);
    let url = url::Url::parse("https://scraper-class.example.com/category/1").unwrap();
    let repo = UrlMetadataRepositoryImpl::new(pool.clone());
    repo.upsert_link(&shop_id, &domain_id, &url, &UrlClass::Category)
        .await
        .unwrap();

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert!(
        !candidates.iter().any(|c| c.url == url),
        "category URL should not be returned as a scraper candidate"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — inactive shop is NOT returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_persist_url_class_other_and_exclude_candidate_when_set_class_is_called() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id =
        insert_shop_with_domain(&pool, shop_id_uuid, "scraper-set-class.example.com").await;
    let target_url = url::Url::parse("https://scraper-set-class.example.com/p/target").unwrap();
    let other_url = url::Url::parse("https://scraper-set-class.example.com/p/other").unwrap();
    let shop_id = shop_core::shop_id::ShopId::from(shop_id_uuid);
    let repo = UrlMetadataRepositoryImpl::new(pool.clone());
    repo.upsert_link(&shop_id, &domain_id, &target_url, &UrlClass::ProductListing)
        .await
        .unwrap();
    repo.upsert_link(&shop_id, &domain_id, &other_url, &UrlClass::ProductListing)
        .await
        .unwrap();

    service
        .set_class(&shop_id, &target_url, UrlClass::Other)
        .await
        .unwrap();

    let target_class: String =
        sqlx::query_scalar("SELECT url_class FROM shop_urls WHERE shop_id = $1 AND url = $2")
            .bind(shop_id_uuid)
            .bind(target_url.to_string())
            .fetch_one(&pool)
            .await
            .unwrap();
    let other_class: String =
        sqlx::query_scalar("SELECT url_class FROM shop_urls WHERE shop_id = $1 AND url = $2")
            .bind(shop_id_uuid)
            .bind(other_url.to_string())
            .fetch_one(&pool)
            .await
            .unwrap();
    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert_eq!(target_class, UrlClass::Other.to_string());
    assert_eq!(other_class, UrlClass::ProductListing.to_string());
    assert!(!candidates.iter().any(|c| c.url == target_url));
    assert!(candidates.iter().any(|c| c.url == other_url));
}

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_not_return_candidate_when_shop_is_inactive() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id =
        insert_shop_with_domain(&pool, shop_id_uuid, "scraper-inactive.example.com").await;
    let url = "https://scraper-inactive.example.com/p/1";
    insert_product_url(&pool, shop_id_uuid, domain_id, url).await;

    sqlx::query("UPDATE shops SET active = FALSE WHERE shop_id = $1")
        .bind(shop_id_uuid)
        .execute(&pool)
        .await
        .unwrap();

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert!(
        !candidates.iter().any(|c| c.url.as_str() == url),
        "candidate for inactive shop should be excluded"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — excluded states (Sold, Removed) are NOT returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_not_return_candidate_when_state_is_excluded() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "scraper-state.example.com").await;

    let shop_id = shop_core::shop_id::ShopId::from(shop_id_uuid);
    let repo = UrlMetadataRepositoryImpl::new(pool.clone());

    let url_sold = url::Url::parse("https://scraper-state.example.com/p/sold").unwrap();
    let url_removed = url::Url::parse("https://scraper-state.example.com/p/removed").unwrap();

    repo.upsert_link(&shop_id, &domain_id, &url_sold, &UrlClass::ProductListing)
        .await
        .unwrap();
    repo.upsert_link(
        &shop_id,
        &domain_id,
        &url_removed,
        &UrlClass::ProductListing,
    )
    .await
    .unwrap();

    repo.set_state(&shop_id, &url_sold, &UrlState::Sold)
        .await
        .unwrap();
    repo.set_state(&shop_id, &url_removed, &UrlState::Removed)
        .await
        .unwrap();

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert!(
        !candidates.iter().any(|c| c.url == url_sold),
        "SOLD URL should not be returned"
    );
    assert!(
        !candidates.iter().any(|c| c.url == url_removed),
        "REMOVED URL should not be returned"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — included states (Available, Listed, Reserved, Unknown)
//                  ARE returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_return_candidate_for_all_included_states() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id =
        insert_shop_with_domain(&pool, shop_id_uuid, "scraper-states.example.com").await;

    let shop_id = shop_core::shop_id::ShopId::from(shop_id_uuid);
    let repo = UrlMetadataRepositoryImpl::new(pool.clone());

    let states = [
        (
            UrlState::Available,
            "https://scraper-states.example.com/p/available",
        ),
        (
            UrlState::Listed,
            "https://scraper-states.example.com/p/listed",
        ),
        (
            UrlState::Reserved,
            "https://scraper-states.example.com/p/reserved",
        ),
        (
            UrlState::Unknown,
            "https://scraper-states.example.com/p/unknown",
        ),
    ];

    for (state, url_str) in &states {
        let url = url::Url::parse(url_str).unwrap();
        repo.upsert_link(&shop_id, &domain_id, &url, &UrlClass::ProductListing)
            .await
            .unwrap();
        repo.set_state(&shop_id, &url, state).await.unwrap();
    }

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    for (_, url_str) in &states {
        assert!(
            candidates.iter().any(|c| c.url.as_str() == *url_str),
            "URL with state that should be included was not returned: {url_str}"
        );
    }
}

// ---------------------------------------------------------------------------
// get_candidates — limit is respected
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_respect_limit_when_multiple_candidates_exist() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "scraper-limit.example.com").await;

    for i in 0..5u32 {
        insert_product_url(
            &pool,
            shop_id_uuid,
            domain_id,
            &format!("https://scraper-limit.example.com/p/{}", i),
        )
        .await;
    }

    let candidates = service.get_candidates(10, 3, &[]).await.unwrap();

    assert_eq!(
        candidates.len(),
        3,
        "get_candidates(10, 3) should return at most 3 URLs from one selected domain"
    );
}

// ---------------------------------------------------------------------------
// get_candidates - random domain-fair fetching caps domains and URLs per domain
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_cap_domains_and_urls_per_domain_when_fetching_candidates() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let hot_shop_id_uuid = uuid::Uuid::new_v4();
    let hot_domain = insert_shop_with_domain(&pool, hot_shop_id_uuid, "fair-hot.example.com").await;
    for i in 0..10u32 {
        insert_product_url(
            &pool,
            hot_shop_id_uuid,
            hot_domain,
            &format!("https://fair-hot.example.com/p/{i}"),
        )
        .await;
    }

    for domain_idx in 0..4u32 {
        let shop_id_uuid = uuid::Uuid::new_v4();
        let domain_name = format!("fair-cold-{domain_idx}.example.com");
        let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, &domain_name).await;
        for url_idx in 0..4u32 {
            insert_product_url(
                &pool,
                shop_id_uuid,
                domain_id,
                &format!("https://{domain_name}/p/{url_idx}"),
            )
            .await;
        }
    }

    let candidates = service.get_candidates(3, 2, &[]).await.unwrap();

    let mut counts_by_host: HashMap<String, usize> = HashMap::new();
    for candidate in &candidates {
        let host = candidate
            .url
            .host_str()
            .expect("candidate URL should have host")
            .to_string();
        *counts_by_host.entry(host).or_default() += 1;
    }

    assert!(
        counts_by_host.len() <= 3,
        "candidate fetch should select at most 3 domains"
    );
    assert!(
        counts_by_host.values().all(|count| *count <= 2),
        "candidate fetch should select at most 2 URLs per domain"
    );
    assert!(
        candidates.len() <= 6,
        "candidate fetch should return at most N * M URLs"
    );
    assert!(
        counts_by_host
            .get("fair-hot.example.com")
            .copied()
            .unwrap_or(0)
            <= 2,
        "hot domain must not fill the whole fetch"
    );
}

// ---------------------------------------------------------------------------
// get_candidates - selected domain set changes across repeated calls
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_randomize_selected_domains_across_repeated_fetches() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    for i in 0..10u32 {
        let shop_id_uuid = uuid::Uuid::new_v4();
        let domain_name = format!("random-domain-{i}.example.com");
        let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, &domain_name).await;
        insert_product_url(
            &pool,
            shop_id_uuid,
            domain_id,
            &format!("https://{domain_name}/p/1"),
        )
        .await;
    }

    let mut observed_sets: std::collections::HashSet<Vec<String>> =
        std::collections::HashSet::new();
    for _ in 0..20 {
        let candidates = service.get_candidates(3, 1, &[]).await.unwrap();
        let mut hosts: Vec<String> = candidates
            .iter()
            .filter_map(|candidate| candidate.url.host_str().map(str::to_string))
            .collect();
        hosts.sort();
        observed_sets.insert(hosts);
    }

    assert!(
        observed_sets.len() > 1,
        "random domain selection should not return the same host set every time"
    );
}

// ---------------------------------------------------------------------------
// get_candidates - selected URLs inside one domain are oldest first
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_order_urls_within_selected_domain_by_oldest_work_first() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "fair-order.example.com").await;
    let never_url = "https://fair-order.example.com/p/never";
    let oldest_url = "https://fair-order.example.com/p/oldest";
    let newer_url = "https://fair-order.example.com/p/newer";
    insert_product_url(&pool, shop_id_uuid, domain_id, newer_url).await;
    insert_product_url(&pool, shop_id_uuid, domain_id, never_url).await;
    insert_product_url(&pool, shop_id_uuid, domain_id, oldest_url).await;

    sqlx::query(
        "UPDATE shop_urls
         SET last_scraped = NOW() - INTERVAL '2 days',
             last_scraped_hash = 'newer'
         WHERE url = $1",
    )
    .bind(newer_url)
    .execute(&pool)
    .await
    .unwrap();
    sqlx::query(
        "UPDATE shop_urls
         SET last_scraped = NOW() - INTERVAL '5 days',
             last_scraped_hash = 'oldest'
         WHERE url = $1",
    )
    .bind(oldest_url)
    .execute(&pool)
    .await
    .unwrap();

    let candidates = service.get_candidates(1, 2, &[]).await.unwrap();
    let urls: Vec<&str> = candidates
        .iter()
        .map(|candidate| candidate.url.as_str())
        .collect();

    assert_eq!(urls, vec![never_url, oldest_url]);
}

// ---------------------------------------------------------------------------
// get_candidates — excluded active domains are NOT returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_not_return_candidate_when_domain_is_excluded() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let blocked_shop_id_uuid = uuid::Uuid::new_v4();
    let blocked_domain =
        insert_shop_with_domain(&pool, blocked_shop_id_uuid, "scraper-blocked.example.com").await;
    insert_product_url(
        &pool,
        blocked_shop_id_uuid,
        blocked_domain,
        "https://scraper-blocked.example.com/p/1",
    )
    .await;

    let open_shop_id_uuid = uuid::Uuid::new_v4();
    let open_domain =
        insert_shop_with_domain(&pool, open_shop_id_uuid, "scraper-open.example.com").await;
    insert_product_url(
        &pool,
        open_shop_id_uuid,
        open_domain,
        "https://scraper-open.example.com/p/1",
    )
    .await;

    let excluded_domains = vec!["scraper-blocked.example.com".to_string()];
    let candidates = service
        .get_candidates(10, 100, &excluded_domains)
        .await
        .unwrap();

    assert!(
        !candidates
            .iter()
            .any(|c| c.url.host_str() == Some("scraper-blocked.example.com")),
        "URL from excluded domain should not be returned"
    );
    assert!(
        candidates
            .iter()
            .any(|c| c.url.host_str() == Some("scraper-open.example.com")),
        "URL from non-excluded domain should still be returned"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — ordering: never-scraped before stale
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_order_never_scraped_before_stale() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "scraper-order.example.com").await;

    let url_never = "https://scraper-order.example.com/p/never";
    let url_stale = "https://scraper-order.example.com/p/stale";
    insert_product_url(&pool, shop_id_uuid, domain_id, url_stale).await;
    insert_product_url(&pool, shop_id_uuid, domain_id, url_never).await;

    // Make the stale one old — scraped 5 days ago with a different hash so it qualifies
    sqlx::query(
        "UPDATE shop_urls \
         SET last_scraped = NOW() - INTERVAL '5 days', last_scraped_hash = 'old' \
         WHERE url = $1",
    )
    .bind(url_stale)
    .execute(&pool)
    .await
    .unwrap();

    let candidates = service.get_candidates(100, 100, &[]).await.unwrap();

    let pos_never = candidates
        .iter()
        .position(|c| c.url.as_str() == url_never)
        .expect("never-scraped URL should be in candidates");
    let pos_stale = candidates
        .iter()
        .position(|c| c.url.as_str() == url_stale)
        .expect("stale URL should be in candidates");

    assert!(
        pos_never < pos_stale,
        "never-scraped (pos {pos_never}) should come before stale (pos {pos_stale})"
    );
}

// ---------------------------------------------------------------------------
// mark_as_scraped — sets last_scraped and last_scraped_hash on the row
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_mark_as_scraped_should_set_last_scraped_and_hash() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "scraper-mark.example.com").await;
    let url_str = "https://scraper-mark.example.com/p/1";
    insert_product_url(&pool, shop_id_uuid, domain_id, url_str).await;

    let shop_id = shop_core::shop_id::ShopId::from(shop_id_uuid);
    let url = url::Url::parse(url_str).unwrap();
    let scraped_hash = "m".repeat(64);

    service
        .mark_as_scraped(&shop_id, &url, &scraped_hash, &minimal_snapshot(url_str))
        .await
        .unwrap();

    let row: (Option<String>, Option<String>) = sqlx::query_as(
        "SELECT last_scraped_hash, last_scraped::text FROM shop_urls WHERE url = $1",
    )
    .bind(url_str)
    .fetch_one(&pool)
    .await
    .unwrap();

    assert_eq!(
        row.0.as_deref(),
        Some(scraped_hash.as_str()),
        "last_scraped_hash should be updated"
    );
    assert!(row.1.is_some(), "last_scraped timestamp should be set");
}

// ---------------------------------------------------------------------------
// mark_as_scraped — after marking, the URL is excluded from get_candidates
//                   (recently scraped)
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_mark_as_scraped_should_exclude_url_from_subsequent_get_candidates() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id =
        insert_shop_with_domain(&pool, shop_id_uuid, "scraper-roundtrip.example.com").await;
    let url_str = "https://scraper-roundtrip.example.com/p/1";
    let hash = "n".repeat(64);
    insert_product_url(&pool, shop_id_uuid, domain_id, url_str).await;

    // Confirm it is returned before marking
    let before = service.get_candidates(10, 100, &[]).await.unwrap();
    assert!(
        before.iter().any(|c| c.url.as_str() == url_str),
        "URL should appear before mark_as_scraped"
    );

    let shop_id = shop_core::shop_id::ShopId::from(shop_id_uuid);
    let url = url::Url::parse(url_str).unwrap();
    service
        .mark_as_scraped(&shop_id, &url, &hash, &minimal_snapshot(url_str))
        .await
        .unwrap();

    // After marking with NOW() timestamp it should no longer appear
    let after = service.get_candidates(10, 100, &[]).await.unwrap();
    assert!(
        !after.iter().any(|c| c.url.as_str() == url_str),
        "URL should not appear after mark_as_scraped"
    );
}

// ---------------------------------------------------------------------------
// get_random_product_urls_for_schema_seed — excludes current URL
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_seed_urls_should_exclude_current_url() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "seed-exclude.example.com").await;

    let exclude_url = "https://seed-exclude.example.com/p/current";
    let other_url = "https://seed-exclude.example.com/p/other";
    insert_product_url(&pool, shop_id_uuid, domain_id, exclude_url).await;
    insert_product_url(&pool, shop_id_uuid, domain_id, other_url).await;

    let shop_id = shop_core::shop_id::ShopId::from(shop_id_uuid);
    let exclude = url::Url::parse(exclude_url).unwrap();
    let sampled = service
        .get_random_product_urls_for_schema_seed(&shop_id, &exclude, 5)
        .await
        .unwrap();

    assert!(
        sampled.iter().all(|u| u.as_str() != exclude_url),
        "excluded URL must never be returned"
    );
    assert!(
        sampled.iter().any(|u| u.as_str() == other_url),
        "another eligible product URL should be sampled"
    );
}

// ---------------------------------------------------------------------------
// get_random_product_urls_for_schema_seed — same shop + product class + states
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_seed_urls_should_only_include_same_shop_product_urls_in_eligible_states() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let seed_shop_uuid = uuid::Uuid::new_v4();
    let seed_domain_id =
        insert_shop_with_domain(&pool, seed_shop_uuid, "seed-filters.example.com").await;
    let seed_shop_id = shop_core::shop_id::ShopId::from(seed_shop_uuid);
    let repo = UrlMetadataRepositoryImpl::new(pool.clone());

    let current_url = url::Url::parse("https://seed-filters.example.com/p/current").unwrap();
    repo.upsert_link(
        &seed_shop_id,
        &seed_domain_id,
        &current_url,
        &UrlClass::ProductListing,
    )
    .await
    .unwrap();

    let eligible_url = url::Url::parse("https://seed-filters.example.com/p/eligible").unwrap();
    repo.upsert_link(
        &seed_shop_id,
        &seed_domain_id,
        &eligible_url,
        &UrlClass::ProductListing,
    )
    .await
    .unwrap();
    repo.set_state(&seed_shop_id, &eligible_url, &UrlState::Available)
        .await
        .unwrap();

    let sold_url = url::Url::parse("https://seed-filters.example.com/p/sold").unwrap();
    repo.upsert_link(
        &seed_shop_id,
        &seed_domain_id,
        &sold_url,
        &UrlClass::ProductListing,
    )
    .await
    .unwrap();
    repo.set_state(&seed_shop_id, &sold_url, &UrlState::Sold)
        .await
        .unwrap();

    let category_url =
        url::Url::parse("https://seed-filters.example.com/category/whatever").unwrap();
    repo.upsert_link(
        &seed_shop_id,
        &seed_domain_id,
        &category_url,
        &UrlClass::Category,
    )
    .await
    .unwrap();

    let other_shop_uuid = uuid::Uuid::new_v4();
    let other_domain_id =
        insert_shop_with_domain(&pool, other_shop_uuid, "seed-other-shop.example.com").await;
    let other_shop_id = shop_core::shop_id::ShopId::from(other_shop_uuid);
    let other_shop_url = url::Url::parse("https://seed-other-shop.example.com/p/other").unwrap();
    repo.upsert_link(
        &other_shop_id,
        &other_domain_id,
        &other_shop_url,
        &UrlClass::ProductListing,
    )
    .await
    .unwrap();

    let sampled = service
        .get_random_product_urls_for_schema_seed(&seed_shop_id, &current_url, 20)
        .await
        .unwrap();

    assert!(
        sampled.iter().any(|u| u == &eligible_url),
        "eligible product URL from same shop should be included"
    );
    assert!(
        sampled.iter().all(|u| u != &current_url),
        "current URL must be excluded"
    );
    assert!(
        sampled.iter().all(|u| u != &sold_url),
        "SOLD URLs must be excluded"
    );
    assert!(
        sampled.iter().all(|u| u != &category_url),
        "non-product URLs must be excluded"
    );
    assert!(
        sampled.iter().all(|u| u != &other_shop_url),
        "URLs from other shops must be excluded"
    );
}

// ---------------------------------------------------------------------------
// get_random_product_urls_for_schema_seed — limit is respected
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_seed_urls_should_respect_limit() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "seed-limit.example.com").await;
    let shop_id = shop_core::shop_id::ShopId::from(shop_id_uuid);

    let current_url = "https://seed-limit.example.com/p/current";
    insert_product_url(&pool, shop_id_uuid, domain_id, current_url).await;

    for i in 0..6u32 {
        insert_product_url(
            &pool,
            shop_id_uuid,
            domain_id,
            &format!("https://seed-limit.example.com/p/{i}"),
        )
        .await;
    }

    let exclude = url::Url::parse(current_url).unwrap();
    let sampled = service
        .get_random_product_urls_for_schema_seed(&shop_id, &exclude, 3)
        .await
        .unwrap();

    assert_eq!(sampled.len(), 3, "query should respect the requested LIMIT");
}
