use crawler::spider::candidate_service::{SpiderCandidateService, SpiderCandidateServiceImpl};
use test_api::*;

const RDS: Rds = Rds {
    sql_setup_file: "src/crawler/sql/schema.sql",
};

/// Helper: inserts a shop + domain and returns the generated domain_id.
async fn insert_shop_with_domain(
    pool: &sqlx::PgPool,
    shop_id_uuid: uuid::Uuid,
    domain: &str,
) -> uuid::Uuid {
    sqlx::query("INSERT INTO shops (shop_id, created, updated) VALUES ($1, NOW(), NOW())")
        .bind(shop_id_uuid)
        .execute(pool)
        .await
        .unwrap();

    insert_domain_for_shop(pool, shop_id_uuid, domain).await
}

/// Helper: inserts only a domain row for an already-existing shop.
async fn insert_domain_for_shop(
    pool: &sqlx::PgPool,
    shop_id_uuid: uuid::Uuid,
    domain: &str,
) -> uuid::Uuid {
    let row: (uuid::Uuid,) = sqlx::query_as(
        "INSERT INTO shop_domains (shop_id, shop_domain) VALUES ($1, $2) RETURNING domain_id",
    )
    .bind(shop_id_uuid)
    .bind(domain)
    .fetch_one(pool)
    .await
    .unwrap();

    row.0
}

// ---------------------------------------------------------------------------
// get_candidates — no eligible shops returns empty vec
// ---------------------------------------------------------------------------

#[serial]
#[localstack_test(services = [RDS])]
async fn should_return_empty_when_no_eligible_candidates_exist() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let candidates = service.get_candidates(10).await.unwrap();

    assert!(
        candidates.is_empty(),
        "expected no candidates for a fresh schema"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — newly-inserted domain (last_crawled IS NULL) is returned
//                  and carries the correct domain_id
// ---------------------------------------------------------------------------

#[serial]
#[localstack_test(services = [RDS])]
async fn should_return_candidate_with_correct_domain_id_when_never_crawled() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "never-crawled.example.com").await;

    let candidates = service.get_candidates(10).await.unwrap();

    assert_eq!(candidates.len(), 1);
    assert_eq!(
        candidates[0].domain_id, domain_id,
        "candidate must carry the domain_id generated by shop_domains"
    );
    assert_eq!(candidates[0].shop_domain, "never-crawled.example.com");
}

// ---------------------------------------------------------------------------
// get_candidates — domain crawled recently is NOT returned
// ---------------------------------------------------------------------------

#[serial]
#[localstack_test(services = [RDS])]
async fn should_not_return_candidate_when_recently_crawled() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "recent.example.com").await;

    // Mark as crawled just now
    sqlx::query("UPDATE shop_domains SET last_crawled = NOW() WHERE domain_id = $1")
        .bind(domain_id)
        .execute(&pool)
        .await
        .unwrap();

    let candidates = service.get_candidates(10).await.unwrap();

    assert!(
        !candidates.iter().any(|c| c.domain_id == domain_id),
        "a domain crawled just now should not be returned as a candidate"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — domain crawled more than 7 days ago IS returned
// ---------------------------------------------------------------------------

#[serial]
#[localstack_test(services = [RDS])]
async fn should_return_candidate_when_crawled_more_than_7_days_ago() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "stale.example.com").await;

    // Set last_crawled to 8 days ago
    sqlx::query(
        "UPDATE shop_domains SET last_crawled = NOW() - INTERVAL '8 days' WHERE domain_id = $1",
    )
    .bind(domain_id)
    .execute(&pool)
    .await
    .unwrap();

    let candidates = service.get_candidates(10).await.unwrap();

    assert!(
        candidates.iter().any(|c| c.domain_id == domain_id),
        "stale domain should be returned with its domain_id"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — inactive shops are excluded
// ---------------------------------------------------------------------------

#[serial]
#[localstack_test(services = [RDS])]
async fn should_not_return_candidate_when_shop_is_inactive() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "inactive-shop.example.com").await;

    // Deactivate the shop
    sqlx::query("UPDATE shops SET active = FALSE WHERE shop_id = $1")
        .bind(shop_id_uuid)
        .execute(&pool)
        .await
        .unwrap();

    let candidates = service.get_candidates(10).await.unwrap();

    assert!(
        !candidates.iter().any(|c| c.domain_id == domain_id),
        "candidates for inactive shops should be excluded"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — limit is respected
// ---------------------------------------------------------------------------

#[serial]
#[localstack_test(services = [RDS])]
async fn should_respect_limit_when_multiple_candidates_exist() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    // Insert 3 shops/domains — all eligible (last_crawled IS NULL)
    for i in 0..3u32 {
        let shop_id_uuid = uuid::Uuid::new_v4();
        insert_shop_with_domain(
            &pool,
            shop_id_uuid,
            &format!("limit-test-{}.example.com", i),
        )
        .await;
    }

    let candidates = service.get_candidates(2).await.unwrap();

    assert_eq!(
        candidates.len(),
        2,
        "get_candidates(2) should return at most 2 results"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — multiple domains on the same shop are each returned
//                  with their own domain_id
// ---------------------------------------------------------------------------

#[serial]
#[localstack_test(services = [RDS])]
async fn should_return_each_domain_separately_for_shop_with_multiple_domains() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    // One shop — two domains. Insert the shop once, then add domains individually.
    let shop_id_uuid = uuid::Uuid::new_v4();
    sqlx::query("INSERT INTO shops (shop_id, created, updated) VALUES ($1, NOW(), NOW())")
        .bind(shop_id_uuid)
        .execute(&pool)
        .await
        .unwrap();

    let domain_id_a = insert_domain_for_shop(&pool, shop_id_uuid, "multi-a.example.com").await;
    let domain_id_b = insert_domain_for_shop(&pool, shop_id_uuid, "multi-b.example.com").await;

    let candidates = service.get_candidates(10).await.unwrap();

    let ids: Vec<uuid::Uuid> = candidates.iter().map(|c| c.domain_id).collect();
    assert!(
        ids.contains(&domain_id_a),
        "domain_id_a should be present in candidates"
    );
    assert!(
        ids.contains(&domain_id_b),
        "domain_id_b should be present in candidates"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — shop_id on the candidate matches the owning shop
// ---------------------------------------------------------------------------

#[serial]
#[localstack_test(services = [RDS])]
async fn should_return_correct_shop_id_on_candidate() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_uuid = uuid::Uuid::new_v4();
    let domain_id = insert_shop_with_domain(&pool, shop_id_uuid, "shopid-check.example.com").await;

    let candidates = service.get_candidates(10).await.unwrap();

    let candidate = candidates
        .iter()
        .find(|c| c.domain_id == domain_id)
        .expect("candidate for the inserted domain should be present");

    let candidate_shop_uuid: uuid::Uuid = candidate.shop_id.into();
    assert_eq!(
        candidate_shop_uuid, shop_id_uuid,
        "candidate.shop_id must match the owning shop"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — ordering: NULL last_crawled comes before stale domains
// ---------------------------------------------------------------------------

#[serial]
#[localstack_test(services = [RDS])]
async fn should_order_never_crawled_before_stale_crawled() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let shop_id_stale = uuid::Uuid::new_v4();
    let shop_id_never = uuid::Uuid::new_v4();

    let domain_id_stale =
        insert_shop_with_domain(&pool, shop_id_stale, "ordering-stale.example.com").await;
    let domain_id_never =
        insert_shop_with_domain(&pool, shop_id_never, "ordering-never.example.com").await;

    // Make one stale
    sqlx::query(
        "UPDATE shop_domains SET last_crawled = NOW() - INTERVAL '10 days' WHERE domain_id = $1",
    )
    .bind(domain_id_stale)
    .execute(&pool)
    .await
    .unwrap();

    // Use a large limit and find both by domain_id to avoid interference from
    // other rows that prior serial tests may have left in the DB.
    let candidates = service.get_candidates(100).await.unwrap();

    let pos_never = candidates
        .iter()
        .position(|c| c.domain_id == domain_id_never)
        .expect("never-crawled domain should be in candidates");
    let pos_stale = candidates
        .iter()
        .position(|c| c.domain_id == domain_id_stale)
        .expect("stale domain should be in candidates");

    assert!(
        pos_never < pos_stale,
        "never-crawled domain (pos {pos_never}) should come before stale domain (pos {pos_stale}) due to NULLS FIRST ordering"
    );
}
