[package]
name = "shop-service"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
shop-core = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
mockall = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true, features = ["serde"] }

fake = { workspace = true, optional = true }
shop-dynamodb = { workspace = true, optional = true }
aws-sdk-dynamodb = { workspace = true, optional = true }
serde_dynamo = { workspace = true, optional = true }
shop-opensearch = { workspace = true, optional = true }
opensearch = { workspace = true, optional = true }

[dev-dependencies]
aws-config = { workspace = true }
time = { workspace = true, features = ["local-offset", "macros", "formatting"] }
rstest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
shop-dynamodb = { workspace = true, features = ["test-data"] }
fake = { workspace = true }
serial_test = { workspace = true }
shop-service = { workspace = true, features = [
    "api",
    "test-data",
    "dynamodb",
    "opensearch",
] }
shop-opensearch = { workspace = true, features = ["test-data"] }

[features]
default = []
api = ["common/api"]
dynamodb = [
    "aws-sdk-dynamodb",
    "serde_dynamo",
    "shop-dynamodb",
    "common/dynamodb",
]
opensearch = ["dep:opensearch", "shop-opensearch"]
test-data = ["fake", "common/test-data", "shop-core/test-data"]
