[package]
name = "product-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["postgres"] }
application = { workspace = true }
search-filter-core = { workspace = true }
user-core = { workspace = true }
async-trait = { workspace = true }
domain-primitives = { workspace = true }
fxrate-core = { workspace = true }
platform-postgres = { workspace = true }
geo = { workspace = true }
indexmap = { workspace = true }
isocountry = { workspace = true }
localization = { workspace = true }
money = { workspace = true }
product-core = { workspace = true }
product-service = { workspace = true }
shop-core = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["formatting", "parsing"] }

url = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
serial_test = { workspace = true }
strum = { workspace = true }
test-api = { workspace = true, features = ["postgres"] }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
