[package]
name = "search-filter-dynamodb"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["dynamodb"] }
search-filter-core = { workspace = true }
item-dynamodb = { workspace = true }
serde = { workspace = true }
field = { workspace = true }
time = { workspace = true, features = ["local-offset", "macros", "formatting"] }
mockall = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
serde_dynamo = { workspace = true, features = [ "aws-sdk-dynamodb+1" ] }

# Optional
fake = { workspace = true, optional = true }

[dev-dependencies]
search-filter-dynamodb = { workspace = true, features = ["test-data"] }
item-dynamodb = { workspace = true, features = ["test-data"] }
test-api = { workspace = true, features = ["dynamodb"] }
serial_test = { workspace = true }
rstest = { workspace = true }

[features]
default = []
test-data = ["fake", "common/test-data", "search-filter-core/test-data", "item-dynamodb/test-data"]
