[package]
name = "search-filter-lambda-opensearch-sync"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "search-filter-lambda-opensearch-sync"
path = "src/main.rs"

[dependencies]
common = { workspace = true, features = ["dynamodb", "event_bridge", "api", "opensearch"] }
search-filter = { workspace = true, features = ["dynamodb", "opensearch"] }
lambda_runtime = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws_lambda_events = { workspace = true, features = ["sqs"] }
serde_json = { workspace = true }
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+1"] }
tokio = { workspace = true, features = ["macros"] }
tracing-subscriber = { workspace = true, features = ["json"] }
tracing = { workspace = true }
opensearch = { workspace = true }
url = { workspace = true }

[dev-dependencies]
test-api = { workspace = true, features = ["opensearch"] }
serial_test = { workspace = true }
uuid = { workspace = true }
fake = { workspace = true }
search-filter = { workspace = true, features = ["test-data"] }
time = { workspace = true, features = ["macros"] }
