[package]
name = "product-classification"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["opensearch"] }
time = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_fields = { workspace = true }
async-trait = { workspace = true }
mockall = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+1"] }
opensearch = { workspace = true }

# Optional
fake = { workspace = true, optional = true }

[dev-dependencies]
product-classification = { workspace = true, features = ["test-data"] }
common = { workspace = true, features = ["test-data"] }
test-api = { workspace = true, features = ["dynamodb", "opensearch"] }
fake = { workspace = true }
serial_test = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[features]
default = []
test-data = ["common/test-data", "fake"]
