[package]
name = "shop-service"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
fake = { workspace = true, optional = true }
async-trait = { workspace = true }
application = { workspace = true }
domain-primitives = { workspace = true }
geo = { workspace = true }
isocountry = { workspace = true }
localization = { workspace = true }
money = { workspace = true }
serde-email = { workspace = true }
shop-core = { workspace = true }
time = { workspace = true, features = ["local-offset", "macros", "formatting"] }
user-core = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }
user-service = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
default = []
test-data = ["fake", "shop-core/test-data", "geo/test-data"]
