[package]
name = "notification-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
application = { workspace = true }
platform-postgres = { workspace = true }
domain-primitives = { workspace = true }
localization = { workspace = true }
money = { workspace = true }
partnership-core = { workspace = true }
party-core = { workspace = true }
listing-source-core = { workspace = true }
notification-core = { workspace = true }
notification-email = { workspace = true }
notification-service = { workspace = true }
product-listing-core = { workspace = true }
search-filter-core = { workspace = true }
serde = { workspace = true, features = ["derive"] }
user-core = { workspace = true }
serde_json = { workspace = true }
serde-email = { workspace = true }
strum = { workspace = true }

sqlx = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
test-api = { workspace = true, features = ["postgres"] }
tokio = { workspace = true, features = ["macros", "rt"] }
