[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
credential-core = { workspace = true }
thiserror = { workspace = true }
user-core = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
