[package]
name = "search-filter-api"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true, features = ["api", "opensearch"] }
search-filter = { workspace = true, features = ["data", "service", "dynamodb"] }
shop = { workspace = true, features = ["dynamodb"] }
product = { workspace = true, features = ["data", "service", "dynamodb", "opensearch"] }
async-trait = { workspace = true }
embedding = { workspace = true }
google-cloud-auth = { workspace = true }
geo = { workspace = true, features = ["data"] }
isocountry = { workspace = true }
product-watchlist = { workspace = true, features = ["data", "service", "dynamodb"] }
product-personalization = { workspace = true }
notification = { workspace = true, features = ["service"] }
user = { workspace = true, features = ["dynamodb", "service", "data"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["macros"] }
aws_lambda_events = { workspace = true, features = ["apigw"] }
lambda_runtime = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
http = { workspace = true }
time = { workspace = true }
futures-util = { workspace = true }

# Optional
fake = { workspace = true, optional = true }

[dev-dependencies]
search-filter-api = { workspace = true, features = ["test-data"] }
test-api = { workspace = true, features = ["api-gateway", "dynamodb", "opensearch"] }
opensearch = { workspace = true }
product = { workspace = true, features = ["test-data"] }
product-watchlist = { workspace = true, features = ["dynamodb"] }
product-personalization = { workspace = true }
notification = { workspace = true, features = ["test-data"] }
user = { workspace = true, features = ["test-data"] }
url = { workspace = true }
serial_test = { workspace = true }
rstest = { workspace = true }
search-filter = { workspace = true, features = ["test-data"] }

[features]
default = []
test-data = ["common/test-data", "fake", "product/test-data", "shop/test-data", "geo/test-data"]
