[package]
name = "product-pipeline-embed-text"
version = "0.1.0"
edition = "2024"

[dependencies]
product-pipeline-common = { workspace = true }
product = { workspace = true, features = ["dynamodb"] }
common = { workspace = true, features = ["dynamodb", "event_bridge"] }
async-trait = { workspace = true }
tracing = { workspace = true }
mockall = { workspace = true }
aws-config = { workspace = true }
aws-sdk-sqs = { workspace = true }
tokio = { workspace = true, features = ["time", "macros", "rt-multi-thread"] }
serde = { workspace = true }
serde_json = { workspace = true }
pyo3 = { workspace = true, features = ["auto-initialize"] }
pyo3-ffi = { workspace = true }

[dev-dependencies]
product-pipeline-common = { workspace = true, features = ["test-data"] }
fake = { workspace = true }
rstest = { workspace = true }
serial_test = { workspace = true }
