name: SonarQube

on:
  push:
    branches: [develop]
    paths:
      - ".github/workflows/sonar.yml"
      - "src/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/prod' }}

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0
  LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_API_KEY }}

jobs:
  sonar:
    name: SonarQube-Cloud Analysis
    permissions:
      contents: read
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt, llvm-tools

      - name: Add Cargo bin to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install grcov
        run: cargo install grcov

      - name: Generate coverage
        env:
          CARGO_PROFILE_TEST_DEBUG: 1
          RUSTFLAGS: "-C instrument-coverage"
          LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"
        run: |
          cargo test --locked --workspace --all-features --exclude smoking-tests --exclude acceptance-tests --exclude product-pipeline-translate -- --nocapture --include-ignored
          grcov . --binary-path ./target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" --ignore "*/target/*" --ignore "*/.cargo/*" -o coverage.lcov

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Clean LLVM coverage artifacts
        run: |
          find . -name "*.profraw" -delete
          rm -f coverage.lcov

      - name: Prune Docker volumes
        run: docker volume prune -f
