[package]
name = "product-enrichment"
version = "0.1.0"
edition = "2024"

[dependencies]
product-pipeline-common = { workspace = true }
product-pipeline-embed-text = { workspace = true }
product-pipeline-translate = { workspace = true }

product = { workspace = true, features = ["service", "opensearch", "dynamodb"] }
common = { workspace = true, features = ["dynamodb", "event_bridge"] }
pyo3 = { workspace = true, features = ["auto-initialize"] }
pyo3-ffi = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
mockall = { workspace = true }
aws-config = { workspace = true }
aws-sdk-autoscaling = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-sqs = { workspace = true }
opensearch = { workspace = true }
tokio = { workspace = true, features = ["time", "macros", "rt-multi-thread"] }
tracing-subscriber = { workspace = true, features = ["json", "time"] }
itertools = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

# Optional deps
fake = { workspace = true, optional = true }
product-enrichment-asg-scale-down = { workspace = true, optional = true }
product-enrichment-asg-scale-up = { workspace = true, optional = true }

[dev-dependencies]
test-api = { workspace = true, features = ["sqs", "dynamodb", "opensearch"] }
serial_test = { workspace = true }
rstest = { workspace = true }
fake = { workspace = true }
uuid = { workspace = true }
time = { workspace = true }
product-enrichment = { workspace = true, features = ["test-data"] }
serde_json = { workspace = true }
serde_dynamo = { workspace = true, features = [ "aws-sdk-dynamodb+1" ] }
aws_lambda_events = { workspace = true, features = [
    "dynamodb",
    "eventbridge",
] }

[features]
default = ["dep:product-enrichment-asg-scale-down"]
test-data = ["fake", "common/test-data", "product/test-data"]
asg-scale-down = ["dep:product-enrichment-asg-scale-down"]
asg-scale-up = ["dep:product-enrichment-asg-scale-up"]
