[package]
name = "product"
version = "0.1.0"
edition = "2024"

[dependencies]
geo = { workspace = true }
isocountry = { workspace = true }
common = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_fields = { workspace = true }
time = { workspace = true, features = ["local-offset", "macros", "formatting"] }
async-trait = { workspace = true }
mockall = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true }
html-escape = { workspace = true }
regex = { workspace = true }
shop = { workspace = true }
tracing = { workspace = true}
indexmap = { workspace = true }

# Optional
field = { workspace = true, optional = true }
fake = { workspace = true, optional = true }
aws-sdk-dynamodb = { workspace = true, optional = true }
aws-sdk-sqs = { workspace = true, optional = true }
opensearch = { workspace = true, optional = true }
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+1"], optional = true }
itertools = { workspace = true, optional = true }
strum = { workspace = true, optional = true }
strum_macros = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }

[dev-dependencies]
aws-config = { workspace = true }
product = { workspace = true, features = ["full"] }
test-api = { workspace = true, features = ["dynamodb", "opensearch", "postgres", "sqs"] }
serial_test = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[features]
default = []
data = ["common/api", "shop/data", "geo/data"]
dynamodb = ["aws-sdk-dynamodb", "serde_dynamo", "common/dynamodb", "field", "strum", "shop/dynamodb"]
opensearch = ["dynamodb", "dep:opensearch", "strum", "strum_macros", "common/opensearch", "shop/opensearch"]
sqs = ["aws-sdk-sqs", "common/sqs"]
service = ["itertools", "shop/dynamodb", "shop/seller", "tokio", "tokio/time", "tokio/sync"]
postgres = ["dep:sqlx", "common/postgres", "service"]
test-data = ["fake", "common/test-data", "shop/test-data", "geo/test-data"]
full = ["data", "dynamodb", "opensearch", "service", "sqs", "postgres", "test-data"]
